---
# =============================================================================
# General common variables

# Times
five_minutes_in_secs: 300
ten_minutes_in_secs: 600
fifteen_minutes_in_secs: 900

