---

# =============================================================================
# Portal setup settings (from fresh server)

# Server settings
# Timezone
webportal_server_set_timezone: True
webportal_server_timezone: "UTC"

# User settings
webportal_user: "user"
webportal_ssh_authorized_keys: "https://raw.githubusercontent.com/SkynetLabs/skynet-webportal/master/setup-scripts/support/authorized_keys"

# Security settings
# geerlingguy.security role vars
security_sudoers_passworded: "{{ [webportal_user] }}"
security_autoupdate_enabled: False
security_fail2ban_enabled: True

# =============================================================================
# Portal deploy settings (on running server)

# Portal
webportal_repo_url: "https://github.com/SkynetLabs/skynet-webportal.git"
webportal_dir: "/home/user/skynet-webportal"
devops_dir: "/home/user/devops"
logs_dir: "{{ devops_dir }}/logs"

# Portal config files (docker-compose.*, .env)
webportal_docker_compose_files_mandatory:
  - "docker-compose.yml"

webportal_docker_compose_files_optional:
  - "docker-compose.accounts.yml"
  - "docker-compose.jaeger.yml"
  - "docker-compose.override.yml"

# Dictionary of optional portal modules defining which docker-compose files
# should be added to docker-compose build/up command.
webportal_docker_compose_files_dict:
  a: "docker-compose.accounts.yml"
  j: "docker-compose.jaeger.yml"

webportal_other_config_files:
  - ".env"

# skynet-js vars
skynet_js_repo_url: "https://github.com/SkynetLabs/skynet-js.git"
skynet_js_docker_test_image: "node:14-buster-slim"

# Local git checkouts
local_temp_skynetlabs_git_repos: "/tmp/SkynetLabs-ansible/git-repos"
local_temp_skynetlabs_git_repos_skynet_js: "{{ local_temp_skynetlabs_git_repos }}/skynet-js"

# Health check disabling delay
portal_health_check_disable_delay_secs: 0

# Waiting for sia full setup and /daemon/ready
sia_full_setup_timeout_secs: 600
sia_daemon_ready_timeout_secs: 600
curl_docker_image: "curlimages/curl:7.77.0"
sia_endpoint_not_available_msg: "491 Module disabled - Refer to API.md"

# docker-compose.override.yml cleaning vars
keep_accounts_services:
  - "nginx"
  - "health-check"
keep_jaeger_services:
  - "sia"

# Localhost vars
# my-logs path relative to ./playbooks directory
local_logs_dir: "../my-logs"
