---

# =============================================================================
# Portal setup settings (from fresh server)

# User settings
webportal_user: "user"
webportal_user_authorized_keys: "https://raw.githubusercontent.com/SkynetLabs/skynet-webportal/master/setup-scripts/support/authorized_keys"

initial_users:
  - username: "{{ webportal_user }}"
    password_hash: "{{ webportal_user_pass_hash }}"
    authorized_keys: "{{ webportal_user_authorized_keys }}"

# Security settings
# geerlingguy.security role vars
security_sudoers_passworded: "{{ [webportal_user] }}"
security_autoupdate_enabled: False
security_fail2ban_enabled: True

# Server settings
# Timezone
webportal_server_set_timezone: True
webportal_server_timezone: "UTC"
# Update server hostname to inventory hostname
webportal_update_hostname: True

# geerlingguy.docker role vars
docker_users: "{{ [webportal_user] }}"

# UFW firewall settings
group_ufw_rules:
  - { rule: 'allow', port: '80', proto: 'tcp', direction: "in" }
  - { rule: 'allow', port: '443', proto: 'tcp', direction: "in" }
ufw_deny_outgoing_to_local_network: True
local_networks:
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"
  - "100.64.0.0/10"
  - "198.18.0.0/15"
  - "169.254.0.0/16"

# LastPass settings
webportal_server_config_lastpass_path: "Shared-Configurations/portal-vars-{{ inventory_hostname }}.yml"
webportal_common_config_lastpass_path: "Shared-Configurations/portal-common-vars.yml"

# Portal settings
webportal_user_home_dir: "/home/{{ webportal_user }}"
webportal_dir: "{{ webportal_user_home_dir }}/skynet-webportal"
devops_dir: "{{ webportal_user_home_dir }}/devops"
logs_dir: "{{ devops_dir }}/logs"
setup_status_dir: "{{ devops_dir }}/setup"
setup_status_file: "{{ setup_status_dir }}/status"
devops_scripts_dir: "{{ devops_dir }}/scripts"
webportal_cron_file: "{{ webportal_dir }}/setup-scripts/support/crontab"

# Sia setup settings
# Wallet initialization
use_existing_sia_seed_if_exists: True

# =============================================================================
# Skynet webportal role settings

webportal_repo_url: "https://github.com/SkynetLabs/skynet-webportal.git"
dotfiles_repo_url: "https://gitlab.com/NebulousLabs/dotfiles.git"

# xxx make optional
webportal_git_config:
  - name: user.name
    value: 'SkynetLabs Devs'
  - name: user.email
    value: "{{ skynetlabs_devs_email }}"

# xxx default in role: False
webportal_setup_dotfiles_and_dev_tools: True

# xxx move to role default vars
webportal_allowance:
  amount: 100KS
  expected_storage: 10TB
  expected_upload: 4TB
  expected_download: 2TB
  expected_redundancy: 5
  max_storage_price: 300SC
  payment_contract_initial_funding: 10SC
  period: 8640b

# xxx move to role default vars
webportal_server_config_defaults:
  domain_name: "{{ ansible_host }}"
  portal_name: "{{ ansible_host }}"
  portal_modules: ""
  sia_wallet_password: ""
  skynet_server_api: "https://{{ ansible_host }}"
  sia_api_port: 9980
  hsd_api_key: "{{ lookup('pipe','openssl rand -base64 32') }}"

# xxx move to role default vars
# xxx default to: False
webportal_setup_health_checks: True

# =============================================================================
# Portal deploy settings (on running server)

# Portal config files (docker-compose.*, .env)
webportal_docker_compose_files_mandatory:
  - "docker-compose.yml"

webportal_docker_compose_files_optional:
  - "docker-compose.accounts.yml"
  - "docker-compose.jaeger.yml"
  - "docker-compose.override.yml"

# Dictionary of optional portal modules defining which docker-compose files
# should be added to docker-compose build/up command.
webportal_docker_compose_files_dict:
  a: "docker-compose.accounts.yml"
  j: "docker-compose.jaeger.yml"

webportal_other_config_files:
  - ".env"

# skynet-js vars
skynet_js_repo_url: "https://github.com/SkynetLabs/skynet-js.git"
skynet_js_docker_test_image: "node:14-buster-slim"

# Local git checkouts
local_temp_skynetlabs_git_repos: "/tmp/SkynetLabs-ansible/git-repos"
local_temp_skynetlabs_git_repos_skynet_js: "{{ local_temp_skynetlabs_git_repos }}/skynet-js"

# Health check disabling delay
portal_health_check_disable_delay_secs: 0

# Waiting for sia full setup and /daemon/ready
sia_full_setup_timeout_secs: 900
sia_daemon_ready_timeout_secs: 600
curl_docker_image: "curlimages/curl:7.77.0"
sia_endpoint_not_available_msg: "491 Module disabled - Refer to API.md"

# docker-compose.override.yml cleaning vars
keep_accounts_services:
  - "nginx"
  - "health-check"
keep_jaeger_services:
  - "sia"

# Localhost vars
# my-logs path relative to ./playbooks directory
local_logs_dir: "../my-logs"
