---
# crap dev machine vars

passworded_users:
  - username: "fil"
    password_hash: "{{ (lookup('community.general.lastpass', 'fil@crap.siasky.net', field='password') | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string)) if (lastpass_required|default(False)) else None }}"

ssh_keys_to_add:
  - user: "fil"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbAhwjJNAud7YIJvLth2bmeUg3kO20xl7ZfqBTvoXn8 fil@siasky.net"

# geerlingguy.security role vars
# List of usernames from passworded_users
security_sudoers_passworded: "{{ passworded_users | map(attribute='username') }}"
security_autoupdate_enabled: False
security_fail2ban_enabled: True

# Custom ufw rules
host_ufw_rules:
  # Vagrant SSH port
  - { rule: 'limit', port: '2222', proto: 'tcp', direction: 'in' }
