---

# Get number of hosts that the running playbook targets
num_hosts: "{{ ansible_play_hosts | length }}"

# Portal
webportal_repo_url: "https://github.com/SkynetLabs/skynet-webportal.git"
webportal_dir: "/home/user/skynet-webportal"
devops_dir: "/home/user/devops"
logs_dir: "{{ devops_dir }}/logs"

# Portal config files (docker-compose.*, .env)
webportal_docker_compose_files:
  - "docker-compose.yml"
  - "docker-compose.accounts.yml"
  - "docker-compose.override.yml"

webportal_other_config_files:
  - ".env"

# skynet-js vars
skynet_js_repo_url: "https://github.com/SkynetLabs/skynet-js.git"
skynet_js_docker_test_image: "node:14-buster-slim"

# Local git checkouts
local_temp_skynetlabs_git_repos: "/tmp/SkynetLabs-ansible/git-repos"
local_temp_skynetlabs_git_repos_skynet_js: "{{ local_temp_skynetlabs_git_repos }}/skynet-js"

# Health check disabling delay
portal_health_check_disable_delay_secs: 0

# Localhost vars
# my-logs path relative to ./playbooks directory
local_logs_dir: "../my-logs"