---

# MongoDB Replicaset Test

- name: Starting a new test
  debug:
    msg: |
      Test: {{ test_item.name }}
      Initial members: {{ test_item.initial_members }}
      Add members: {{ test_item.add_members | default([])}}

- name: Remove mongo containers (if exist)
  docker_container:
    name: "mongo-{{ item }}"
    state: absent
    container_default_behavior: no_defaults
  loop: "{{ test_config.mongo_indices }}"

- name: Remove test directory
  ansible.builtin.file:
    path: "{{ webportal_user_home_dir }}/mongo-cluster-test"
    state: absent
  become: True

- name: Ensure mgkey parent directory exists
  ansible.builtin.file:
    path: "{{ webportal_user_home_dir }}/mongo-cluster-test/docker/data/mongo-{{ item }}"
    state: directory
  become: True
  loop: "{{ test_config.mongo_indices }}"

- name: Ensure mgkey with content file exists
  ansible.builtin.copy:
    content: "{{ webportal_common_config.mongo_db_mgkey }}"
    dest: "{{ webportal_user_home_dir }}/mongo-cluster-test/docker/data/mongo-{{ item }}/mgkey"
    owner: "999"
    group: "999"
    mode: "0400"
  become: True
  loop: "{{ test_config.mongo_indices }}"

- name: Start MongoDB docker containers
  community.docker.docker_container:
    name: "mongo-{{ item }}"
    published_ports: "2701{{ item }}:2701{{ item }}"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ accounts_config.skynet_db_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ accounts_config.skynet_db_password }}"
    volumes: "{{ webportal_user_home_dir }}/mongo-cluster-test/docker/data/mongo-{{ item }}:/data"
    image: "{{ test_config.mongo_image}}"
    command: "--keyFile=/data/mgkey --replSet={{ webportal_common_config.mongo_db_replicaset_name }} --port 2701{{ item }}"
    container_default_behavior: "no_defaults"
    networks:
      - name: "skynet-webportal_shared"
    # Note: We set network_mode to get rid of depreciation warning.
    network_mode: "default"
  loop: "{{ test_config.mongo_indices }}"

- name: Wait for MongoDB containers to be ready
  community.mongodb.mongodb_shell:
    login_host: "{{ webportal_server_config.domain_name }}"
    login_port: "2701{{ item }}"
    login_user: "{{ accounts_config.skynet_db_user }}"
    login_password: "{{ accounts_config.skynet_db_password }}"
    mongo_cmd: "docker exec mongo-{{ item }} mongo"
    eval: "rs.status()"
  register: mongo_wait_result
  until:
    - mongo_wait_result.transformed_output is defined
    - mongo_wait_result.transformed_output.ok == 1 or mongo_wait_result.transformed_output.codeName == 'NotYetInitialized'
  delay: 1
  retries: 60
  loop: "{{ test_config.mongo_indices }}"

- name: Include initializing MongoDB replicaset
  include_tasks: tasks/docker-mongo-init-replicaset.yml
  vars:
    docker_mongo_replicaset:
      members: "{{ test_item.initial_members }}"
      container_name: "mongo-1"
      host: "localhost"
      port: "27011"
      user: "{{ accounts_config.skynet_db_user }}"
      password: "{{ accounts_config.skynet_db_password }}"

# Add non-voting member (test cluster specific)
# xxxqqq add members - add voting, non-voting switch

- name: Add non-voting member(s) to MongoDB replicaset
  block:
    - name: Include getting primary MongoDB member
      include_tasks: tasks/docker-mongo-get-primary.yml
      vars:
        docker_mongo_replicaset_primary:
          container_name: "mongo-2"
          host: "localhost"
          port: "27012"
          user: "{{ accounts_config.skynet_db_user }}"
          password: "{{ accounts_config.skynet_db_password }}"

    - name: Set MongoDB primary port
      set_fact:
        mongo_primary_port: "{{ mongo_primary_host_port.split(':')[1] }}"

    - name: Set MongoDB primary container name
      set_fact:
        mongo_primary_container: "mongo-{{ mongo_primary_port | int - 27010 }}"

    - name: Add MongoDB non-voting member
      include_tasks: tasks/docker-mongo-add-non-voting-member.yml
      vars:
        docker_mongo_replicaset_add_non_voting:
          member: "{{ add_member_item }}"
          container_name: "{{ mongo_primary_container }}"
          host: "localhost"
          port: "{{ mongo_primary_port | int }}"
          user: "{{ accounts_config.skynet_db_user }}"
          password: "{{ accounts_config.skynet_db_password }}"
      loop: "{{ test_item.add_members | list }}"
      loop_control:
        loop_var: "add_member_item"
  when: test_item.add_members | default([]) != []

- name: Check final MongoDB replicaset config and status
  block:
    # Check MongoDB replicaset config

    - name: Get MongoDB replicaset (filtered) config
      community.mongodb.mongodb_shell:
        login_host: "{{ webportal_server_config.domain_name }}"
        login_port: "27012"
        login_user: "{{ accounts_config.skynet_db_user }}"
        login_password: "{{ accounts_config.skynet_db_password }}"
        mongo_cmd: "docker exec mongo-2 mongo"
        eval: |
          let cfg = rs.config();
          let filteredCfg = {};
          let filteredMembers = [];

          cfg.members.forEach((m) => filteredMembers.push({"host": m.host, "priority": m.priority, "votes": m.votes}));
          
          filteredCfg._id = cfg._id;
          filteredCfg.members = filteredMembers;
          
          printjson(filteredCfg);
      register: mongo_config_result

    - name: Log MongoDB replicaset config
      debug:
        var: mongo_config_result
    
    - name: Fail if we didn' get replicaset config
      fail:
        msg: We didn't get expected replicaset config data
      when: mongo_config_result.transformed_output is not defined or mongo_config_result.transformed_output._id is not defined or mongo_config_result.transformed_output.members is not defined

    - name: Fail if MongoDB replicaset id is not set correctly in config
      fail:
        msg: |
          Replicaset id in config doesn't match:

          Expected: {{ webportal_common_config.mongo_db_replicaset_name }}
          Actual: {{ mongo_config_result.transformed_output._id }}
      when: mongo_config_result.transformed_output._id != webportal_common_config.mongo_db_replicaset_name
    
    - name: Set final MongoDB replicaset members config
      set_fact:
        # Merge initial members and added members,
        # if not defined set priority = 1, votes =  1.
        mongo_final_members: "{{ mongo_final_members | default([]) + [item | combine({'priority': (item.priority | default(1)), 'votes': (item.votes | default(1))})] }}"
      loop: "{{ test_item.initial_members + test_item.add_members }}"

    - name: Fail if expected MongoDB replicaset members are not present in current replicaset config
      fail:
        msg: |
          Member {{ item }} is expected to be present in replicaset config,
          but it is missing.
      when: item not in mongo_config_result.transformed_output.members
      loop: "{{ mongo_final_members }}"
    
    # Check MongoDB replicaset status

    - name: Get MongoDB replicaset (filtered) status
      community.mongodb.mongodb_shell:
        login_host: "{{ webportal_server_config.domain_name }}"
        login_port: "27012"
        login_user: "{{ accounts_config.skynet_db_user }}"
        login_password: "{{ accounts_config.skynet_db_password }}"
        mongo_cmd: "docker exec mongo-2 mongo"
        eval: |
          let sts = rs.status();
          let filteredSts = {};
          let filteredMembers = [];

          sts.members.forEach((m) => filteredMembers.push({"name": m.name, "health": m.health, "stateStr": m.stateStr}));
          
          filteredSts.set = sts.set;
          filteredSts.ok = sts.ok;
          filteredSts.members = filteredMembers;
          
          printjson(filteredSts);
      register: mongo_status_result

    - name: Log MongoDB replicaset status
      debug:
        var: mongo_status_result
    
    - name: Fail if we didn' get replicaset status
      fail:
        msg: We didn't get expected replicaset status data
      when: (mongo_status_result.transformed_output is not defined) or (mongo_status_result.transformed_output.ok | default(-1) != 1) or (mongo_status_result.transformed_output.set is not defined) or (mongo_status_result.transformed_output.members is not defined)

    - name: Fail if MongoDB replicaset id is not correct in status
      fail:
        msg: |
          Replicaset id in status doesn't match:

          Expected: {{ webportal_common_config.mongo_db_replicaset_name }}
          Actual: {{ mongo_status_result.transformed_output.set }}
      when: mongo_status_result.transformed_output.set != webportal_common_config.mongo_db_replicaset_name

    - name: Fail if there is not exactly 1 PRIMARY member
      fail:
        msg: |
          There is not exactly 1 PRIMARY member:

          Members: {{ mongo_status_result.transformed_output.members }}
      when: mongo_status_result.transformed_output.members | map(attribute='stateStr') | reject('==', 'PRIMARY') | length != mongo_status_result.transformed_output.members - 1

    - name: Fail if there is not expected number of members in replicaset status
      fail:
        msg: |
          MongoDB number of members in replicase doesn't match:

          Expected members: {{ mongo_final_members | length }}
          Actual members: {{ mongo_status_result.transformed_output.members | lenght }}
      when: mongo_status_result.transformed_output.members | lenght != mongo_final_members | length
