---
# Update apt
- name: Run apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 900

# Install latest sudo
- name: Install sudo
  apt:
    name: sudo
    state: latest

# Create users with defined uid
- name: Create users with defined uid
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password_hash }}"
    gid: "item.gid"
    state: present
    shell: /bin/bash
    groups:
      - sudo
  # Below must be exact case: None (Python), none (Jinja test)
  when: item.gid | default(None) is not none
  loop: "{{ initial_users }}"

# Create users without defined uid
- name: Create users without defined uid
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password_hash }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
  # Below must be exact case: None (Python), none (Jinja test)
  when: item.gid | default(None) is none
  loop: "{{ initial_users }}"

# Remove temp user
- name: Remove temp user (when webportal user is active)
  ansible.builtin.user:
    name: "{{ webportal_temp_user }}"
    state: absent
    remove: yes
  when: ansible_user == webportal_user

# Add SSH authorized keys
- name: Add SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.authorized_keys }}"
  loop: "{{ initial_users }}"
  when: webportal_user_authorized_keys != ""

# Basic security
- name: Include basic security setup
  include_role:
    name: geerlingguy.security
