---
# Update apt
- name: Run sudo apt-get update
  become: true # only needed when not root user
  apt:
    update_cache: yes
    cache_valid_time: 900

# Install latest sudo
- name: Install sudo
  become: true # only needed when not root user
  apt:
    name: sudo
    state: latest

# Create user
- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password_hash }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
  loop: "{{ initial_users }}"

# Add SSH authorized keys
- name: Add SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.authorized_keys }}"
  loop: "{{ initial_users }}"

# Basic security
- name: Include basic security setup
  include_role:
    name: geerlingguy.security
