---

# Remove MongoDB member

- name: Assert we have all arguments
  assert:
    that:
      - docker_mongo_replicaset_remove.member | default({}) != {}
      - docker_mongo_replicaset_remove.container_name | default('') != ''
      - docker_mongo_replicaset_remove.host | default('') != ''
      - docker_mongo_replicaset_remove.port | default('') != ''
      - docker_mongo_replicaset_remove.user | default('') != ''
      - docker_mongo_replicaset_remove.password | default('') != ''

- name: Remove MongoDB member
  community.mongodb.mongodb_shell:
    login_host: "{{ docker_mongo_replicaset_remove.host }}"
    login_port: "{{ docker_mongo_replicaset_remove.port }}"
    login_user: "{{ docker_mongo_replicaset_remove.user }}"
    login_password: "{{ docker_mongo_replicaset_remove.password }}"
    mongo_cmd: "docker exec {{ docker_mongo_replicaset_remove.container_name }} mongo"
    # Single quotes are needed for host value below.
    eval: |
      rs.remove('{{ remove_member_item.host }}')
    # transform_output can't be parsed correctly by this module, keep it raw
    transform: raw
  register: mongo_remove_result

- name: Fail if removing member was not successful
  fail:
    msg: |
      Removing a member failed, see mongo shell output:
      
      {{ mongo_remove_result.transformed_output }}
  when: |-
    (mongo_remove_result.transformed_output | default('') == '') or ((mongo_remove_result.transformed_output | replace('\t', '') | replace(' : ', ':')).find('"ok":1,') == -1)
