---
# Setup ufw firewall

- name: Install ufw firewall
  apt:
    name: ufw
    state: present

- name: Set ufw defaults
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - reload ufw firewall

- name: Set ufw rules
  vars:
    default_ufw_rule: { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    "{{ [default_ufw_rule] + (ufw_rules | default([])) }}"
  notify:
    - reload ufw firewall

# xxxqqq
# - name: Deny outgoing traffic to local network 
#   community.general.ufw:
#     rule: "deny"
#     proto: "any"
#     to_ip: "{{ item }}"
#   loop:
#     - "10.0.0.0/8"
#     - "172.16.0.0/12"
#     - "192.168.0.0/16"
#     - "100.64.0.0/10"
#     - "198.18.0.0/15"
#     - "169.254.0.0/16"
#   notify:
#     - reload ufw firewall
#   when: ufw_deny_outgoing_to_local_network | default(False)

- name: Enable ufw firewall
  community.general.ufw:
    state: enabled
    logging: low
  notify:
    - reload ufw firewall

- name: Reload ufw if needed
  meta: flush_handlers