---

# Limit number of hosts that can be targeted by a playbook execution
- name: Fail if you are targeting more then max_hosts
  vars:
    # Get number of hosts that the running playbook targets
    num_hosts: "{{ ansible_play_hosts_all | length }}"
  fail:
    msg: |
      You are executing the playbook on {{ num_hosts }} hosts
      which is more than maximum allowed {{ max_hosts }} hosts for this playbook.
      
      E.g. you can't target all dev and prod webportals at once in some playbooks.
      
      Use '--limit' command line flag, e.g.:
      
          ... --limit host1,host2
          ... --limit group1,group2
  when: num_hosts | int > max_hosts | int
