---
# Load yaml or json secure note from LastPass to Ansible variable

# This tasks is supposed to be called (included) in a loop with list of
# dictionaries defining secret_path and var_name.
# Example:
#
# - name: Load LastPass data
#   include_tasks: tasks/lastpass-load-secret-yaml-or-json.yml
#   loop:
#     - secret_path: "Shared-Data/abc.yml"
#       var_name: abc
#     - secret_path: "Shared-Data/other-var.json"
#       var_name: some_other_var_name
#
# Value of `secret_path` must end either with `.yml` or with `.json` otherwise
# the task can't determine the secure note format and fails the playbook.

# Output:
# This task sets output variable (var_name) value according to the data from
# the given LastPass path (secret_path).
#
# - If the given path doesn't exists in LastPass,
#   the output variable is not defined.
# - If the secured note at the given path in LastPass is empty
#   the ouptput variable is empty dictionary, i.e. {}.
# - Otherwise yaml or json data (based on secret_path extension) from secure
# note are loaded into output variable.

- name: Assert we can determine secure note format
  ansible.builtin.assert:
    that:
      - item.secret_path.endswith('.yml') or item.secret_path.endswith('.json')
    fail_msg: |
      Loading LastPass secure notes supports only notes with path ending with
      `.yml` or `.json`.

      Current lastpass path:
      {{ item.secret_path }}

- name: Check if LastPass item exists
  delegate_to: localhost
  ansible.builtin.command: "lpass ls --sync now '{{ item.secret_path }}'"
  register: lastpass_ls_result
  changed_when: False

- block:
    - name: Get LastPass data
      delegate_to: localhost
      ansible.builtin.command: "lpass show --sync now '{{ item.secret_path }}'"
      register: lastpass_show_result
      changed_when: False

    - name: Remove unwanted LastPass data beginning
      set_fact:
        # The stdout_lines contain 2 lines that we don't want, and then the
        # third line starts with 'Notes: ' and contains the first config field,
        # so we want to trim that.
        lastpass_data: "{{ lastpass_show_result.stdout_lines[2:] | join('\n') | replace('Notes: ', '') }}"

    - name: Parse LastPass data to yaml
      set_fact:
        parsed_data: "{{ lastpass_data | from_yaml }}"
      when: item.secret_path.endswith('.yml')

    - name: Pass LastPass data
      set_fact:
        # lastpass_data are already dictionary, we can't use `| from_json` here.
        parsed_data: "{{ lastpass_data }}"
      when: item.secret_path.endswith('.json')

    - name: Set variable value from LastPass data
      set_fact:
        "{{ item.var_name }}": "{{ {} if parsed_data == '' else parsed_data }}" # noqa var-naming
  when: lastpass_ls_result.stdout != ''
