---
- name: Check if webportal user credentials LastPass record exists
  local_action:
    module: ansible.builtin.command
    cmd: "lpass ls --sync now {{ lastpass_portal_credentials_server }}"
  register: lastpass_ls_result

# Create and save webportal user password to LastPass (if missing in LastPass)
- block:
    - name: Set webportal user password
      set_fact:
        ansible_become_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

    - name: Create LastPass record
      local_action:
        module: shell
        cmd: "printf 'URL: {{ ansible_host }}\nUsername: {{ webportal_user }}\nPassword: {{ ansible_become_pass }}' | lpass add --sync now {{ lastpass_portal_credentials_server }} --non-interactive"

  when: lastpass_ls_result.stdout_lines | length == 0
