---

# Check if there are any variables loaded from LastPass and the LastPass
# session is active

# Evaluate all host vars (for each host active in the play)
# This task fails if there is a host var requiring LastPass and the LastPass
# session is not active.
- name: Evaluate all host vars (for each host active in the play)
  set_fact:
    dummy: "{{ hostvars[inventory_hostname] }}"
  ignore_errors: True
  register: host_vars_check

# Check all other vars (except host vars)
# This task fails if there is a (non-host) var requiring LastPass and the
# LastPass session is not active.
- name: Check all other vars (except host vars)
  set_fact:
    dummy: "{{ lookup('vars', item) }}"
  when: not host_vars_check.failed and item != 'hostvars'
  loop: "{{ vars.keys() }}"
  ignore_errors: True
  register: other_vars_check

# Fail if there are some vars loaded from LastPass and LastPass session is not
# active
- name: Fail if there are some vars loaded from LastPass and LastPass session is not active
  fail:
    msg: "Your LastPass session is not active.\nExecute:\n\n    scripts/lastpass-login.sh\n"
  when: host_vars_check.failed or (other_vars_check.failed is defined and other_vars_check.failed)