---

- name: Check if LastPass record exists
  local_action:
    module: ansible.builtin.command
    cmd: "lpass ls {{ webportal_server_config_lastpass_path }}"
  register: lastpass_ls_result

- name: Set LastPass command add or edit
  set_fact:
    lastpass_command: "{{ 'add' if lastpass_ls_result.stdout_lines | length == 0 else 'edit' }}"

- name: Update LastPass record
  local_action:
    module: shell
    cmd: >
      printf '{{ webportal_server_config | to_nice_yaml(width=2048) }}'
      | lpass {{ lastpass_command }} --notes --non-interactive {{ webportal_server_config_lastpass_path }}
  no_log: True
