---

- name: Check if webportal user credentials LastPass record exists
  local_action:
    module: ansible.builtin.command
    cmd: "lpass ls {{ lastpass_portal_credentials_server }}"
  register: lastpass_ls_result

# xxxqqq delete
# - name: Set LastPass command add or edit
#   set_fact:
#     lastpass_command: "{{ 'add' if lastpass_ls_result.stdout_lines | length == 0 else 'edit' }}"

# xxxqqq delete
# - name: Update LastPass record
#   local_action:
#     module: shell
#     cmd: printf '{{ webportal_server_config | to_nice_yaml(width=2048) }}' | lpass {{ lastpass_command }} --notes --non-interactive {{ lastpass_portal_config_server }}
#   no_log: True

# - name: Generate webportal user password (if missing in LastPass)
#   when:

# Create and save webportal user password to LastPass (if missing in LastPass)
- block:
    - name: Set webportal user password
      set_fact:
        ansible_become_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

    - name: Create LastPass record
      local_action:
        module: shell
        cmd: "printf 'URL: {{ ansible_host }}\nUsername: {{ webportal_user }}\nPassword: {{ ansible_become_pass }}' | lpass add {{ lastpass_portal_credentials_server }} --non-interactive"

  when: lastpass_ls_result.stdout_lines | length == 0