---

# Load Portal server and common configs from LastPass

- name: Include loading LastPass portal server config
  include_tasks: tasks/lastpass-load-webportal-server-config.yml

- name: Include loading LastPass portal common config
  include_tasks: tasks/lastpass-load-webportal-common-config.yml

- name: Include loading LastPass portal cluster config
  include_tasks: tasks/lastpass-load-webportal-cluster-config.yml
