---
# Prepare Skynet Webportals for our Ansible playbooks

# xxx requires sudo pass
# # Install python3-pip
# - name: Install python3-pip
#   apt:
#     name: "python3-pip"
#     state: latest
#   become: True

# Install Docker and docker-compose SDKs for Python
- name: Install Docker and docker-compose SDKs for Python
  pip:
    name:
      - docker==5.0.3
      - docker-compose==1.29.2

# Create devops/logs dir to log activity
- name: Create devops/logs directory
  ansible.builtin.file:
    path: "{{ logs_dir }}"
    state: directory
    owner: "user"
    group: "user"
    mode: "0700"
