---
# Execute any defined docker/shell command(s).
# This loops over all the docker/shell commands listed and executes them one at a
# time. Variable docker_commands is depreciated, shell_commands should be used
# instead.
- name: Executing shell command(s)
  vars:
    commands: "{{ (docker_commands | default([])) + (shell_commands | default([])) }}"
  ansible.builtin.shell: "{{ item }}"
  loop: "{{ commands }}"
  when: docker_commands is defined or shell_commands is defined

# Block any defined hosts
- name: Block any bad hosts
  ansible.builtin.command: "docker exec sia siac hostdb block {{ item }}"
  loop: "{{ hostdb_blocked_domains }}"
  when: hostdb_blocked_domains is defined

# Unblock any defined hosts
- name: Unblock hosts
  ansible.builtin.command: "docker exec sia siac hostdb unblock {{ item }}"
  loop: "{{ hostdb_unblock_domains }}"
  when: hostdb_unblock_domains is defined
