---

# Get remote portal files modified after last Ansible docker services start

# find all files (excluding files in .git and docker/data directories) that are
# modified after latest '*.status.*' files (which was saved on latest Ansible
# docker services re-/start)
- name: Get modified files
  ansible.builtin.shell:
    cmd: |
      find \( -path "./.git" -o -path "./docker/data" -o -path "./logs" \) ! -prune -o -type f -newer "{{ logs_dir }}"/$(ls "{{ logs_dir }}" | grep \.status\. | tail -n1)
  args:
    chdir: "{{ webportal_dir }}"
  register: portal_modified_files

- debug:
    msg:
      - "Versions set in portal files:"
      - "  git tag: {{ portal_repo_tag }}"
      - "  git branch: {{ portal_repo_branch }}"
      - "  git commit {{ portal_repo_commit }}"
      - ""
      - "  portal_repo_version: {{ portal_repo_version }}"
      - "  portal_skyd_version: {{ portal_skyd_version_used }}"
      - "  portal_accounts_version: {{ portal_accounts_version_used }}"
      - ""
      - "Following files were edited after last Ansible docker services re-/start:"
      - "{{ portal_modified_files.stdout.split('\n') }}"
  failed_when: portal_modified_files.stdout != ""