---
# Get remote portal files modified after last Ansible docker services start

# find all files (excluding files in .git, docker/data and
# /docker/kratos/cr_certs/backup directories) that are modified after latest
# '*.status.*' file (which was saved on latest Ansible docker services
# re-/start)
- name: Get modified files
  ansible.builtin.shell:
    cmd: |
      find \( -path "./.git" -o -path "./docker/data" -o -path "./logs" -o -path "./docker/kratos/cr_certs/backup" \) ! -prune -o -type f -newer "{{ logs_dir }}"/$(ls "{{ logs_dir }}" | grep \.status\. | tail -n1)
  args:
    chdir: "{{ webportal_dir }}"
  register: portal_modified_files
