---
# Run MongoDB shell command
# TODO: This ansible playbook task, should be copied to portal role and also
# kept for playbooks.

- name: Run mongo shell command
  community.mongodb.mongodb_shell:
    # Use secure localhost connection unless `use_custom_mongo_host` is set to
    # True to allow for handling of testing setups where multiple nodes are
    # running on local host and so the ansible_host needs to be used.
    login_host: "{{ 'localhost' if (not (use_custom_mongo_host | default('False'))) else ansible_host }}"
    login_port: "{{ custom_mongo_port | default(default_mongo_port | string) }}"
    login_user: "{{ webportal_common_config.skynet_db_user | default(mongodb_config.skynet_db_user) }}"
    login_password: "{{ webportal_common_config.skynet_db_pass | default(mongodb_config.skynet_db_pass) }}"
    mongo_cmd: "docker exec mongo mongo"
    eval: "{{ mongodb_shell.eval }}"
    # transformed_output can't be parsed correctly by this module, keep it raw
    transform: raw
  register: mongo_shell_result
  until: mongodb_shell.until
  delay: 1
  retries: "{{ mongodb_shell.retries }}"
  ignore_errors: "{{ mongodb_shell.ignore_errors | default(False) }}"
