---

# Set SSH authentication socket fact on delegated host

# Note: Registered results are not delegated to 'delegate_to' hosts, they are
# kept as facts on the current host, so we must throttle setting registered
# result so it is set on correct delegated host (the fact is used later on the
# delegated host).

- block:
    - name: Get SSH auth socket on remote machine (so we can forward it to rsync container)
      command: echo "$SSH_AUTH_SOCK"
      register: ssh_auth_sock_result
      delegate_to: "{{ item.dest_host }}"

    - name: Set SSH authentication socket on delegated host
      set_fact:
        ssh_auth_sock: "{{ hostvars[inventory_hostname].ssh_auth_sock_result.stdout }}"
      delegate_to: "{{ item.dest_host }}"
      delegate_facts: True
  throttle: 1
