---

# Ensure MongoDB node is member of the MongoDB replicaset
# TODO: This ansible playbook task, should be moved to portal role

# Notes:
# - MongoDB primary node tasks should be executed on {{ mongo_primary_host }},
#   not on the current Ansible host that we are handling.

- name: Include getting MongoDB replicaset primary host
  include_tasks: tasks/portal-role-task-mongo-replicaset-get-status.yml

- name: Include checking if MongoDB node is part of the replicaset
  include_tasks: tasks/portal-role-task-mongo-shell-eval-on-delegated-host.yml
  vars:
    mongodb_shell_delegated:
      host: "{{ mongo_primary_host }}"
      user: "{{ skynet_db_user_result.stdout }}"
      password: "{{ skynet_db_pass_result.stdout }}"
      eval: |
        rs.config().members.forEach(m => {
          if (m.host == '{{ ansible_host }}:{{ subcrap_mongo_port | default(default_mongo_port | string) }}')
          {
            print('is-member')
          }
        })

- name: Set host in MongoDB replicaset configuration
  set_fact:
    host_in_replicaset: "{{ mongo_shell_delegated_result.transformed_output == 'is-member' }}"

- name: Log whether MongoDB node is in replicaset configuration
  debug:
    msg: |
      Ansible host: {{ inventory_hostname }}
      MongoDB host: {{ ansible_host }}:{{ subcrap_mongo_port | default(default_mongo_port | string) }}

      MongoDB host in replicaset configuration: {{ host_in_replicaset }}

- name: Include adding MongoDB node as non-voting member to replicaset configuration
  include_tasks: tasks/portal-role-task-mongo-shell-eval-on-delegated-host.yml
  vars:
    mongodb_shell_delegated:
      host: "{{ mongo_primary_host }}"
      user: "{{ skynet_db_user_result.stdout }}"
      password: "{{ skynet_db_pass_result.stdout }}"
      eval: |
        rs.add({host: '{{ ansible_host }}:{{ subcrap_mongo_port | default(default_mongo_port | string) }}', priority: 0, votes: 0})
  when: not host_in_replicaset
  register: mongo_adding_non_voting_result

- name: Fail if adding a MongoDB node to replicaset config was not successful
  fail:
    msg: |
      Add MongoDB node to replicaset result: {{ mongo_shell_delegated_result | to_nice_json }}

      Add MongoDB node to replicaset transformed_output: {{ mongo_shell_delegated_result.transformed_output | default('') }}
  when: >-
    not (mongo_adding_non_voting_result.skipped | default(False)) and
    (mongo_shell_delegated_result.failed | default(False) or
    mongo_shell_delegated_result.transformed_output is not defined or
    '\"ok\" : 1,' not in mongo_shell_delegated_result.transformed_output)

- name: Wait till MongoDB node is part of the replicaset
  include_tasks: tasks/portal-role-task-mongo-shell-eval-on-delegated-host.yml
  vars:
    mongodb_shell_delegated:
      host: "{{ mongo_primary_host }}"
      eval: |
        rs.config().members.forEach(m => {
          if (m.host == '{{ ansible_host }}:{{ subcrap_mongo_port | default(default_mongo_port | string) }}')
          {
            print('is-member')
          }
        })
  register: is_replicaset_member_result
  until: 'is-member' is in is_replicaset_member_result.stdout
  delay: 1
  retries: 120