---

# Prepeare server for portal setup

# Install required packages
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-pip
    - git
  become: True

# Install Docker
- name: Include role to install Docker
  include_role:
    name: geerlingguy.docker
    apply:
      become: True

# Reset SSH connection to reload new user groups (docker)
- name: Reset SSH connection to reload new user groups (docker)
  ansible.builtin.meta:
    reset_connection

# Install required Python modules
- name: Install required Python modules
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-compose
    - pexpect

# Set timezone
- name: Set timezone
  community.general.timezone:
    name: "{{ webportal_server_timezone }}"
  become: True
  when: webportal_server_set_timezone | default(False)
