---

# Clean Portal sia/renter/renter.log file

# Note: This task should be performed while sia is stopped

- name: Pull Alpine image
  community.docker.docker_image:
    name: alpine:3.15.0
    source: pull

- name: Clean renter.log file
  community.docker.docker_container:
    name: clean-renter-logs
    image: alpine:3.15.0
    volumes:
      - "{{ webportal_dir }}/docker/data/sia/renter:/sia-renter"
    command: "sed -i '/{{ item }}/d' /sia-renter/renter.log"
    container_default_behavior: no_defaults
    detach: False
    auto_remove: True
  loop:
    - "pt not ready yet for worker"
    - "HEALTH LOOP VERBOSE"
    - "dirupdatebatch completed"
