---
# Get remote portal branch and commit

- name: Get remote portal repo tag (if set at the current commit)
  ansible.builtin.command:
    chdir: "{{ webportal_dir }}"
    cmd: git tag --points-at HEAD
  register: port_git_all_tags
  failed_when: False

- name: Set remote portal repo all tags
  set_fact:
    portal_repo_all_tags: "{{ port_git_all_tags.stdout | replace('\n', ',') }}"

- name: Set remote portal repo tag
  set_fact:
    portal_repo_tag: "{{ '' if (port_git_all_tags.stdout_lines[-1:] == []) else port_git_all_tags.stdout_lines[-1:][0] }}"

- name: Set remote portal repo version (tag)
  set_fact:
    portal_repo_version: "{{ portal_repo_tag }}"
  when: portal_repo_tag != ''

- name: Get remote portal repo branch
  ansible.builtin.command:
    chdir: "{{ webportal_dir }}"
    cmd: git symbolic-ref --short HEAD
  register: port_git_branch
  failed_when: False

- name: Set remote portal repo branch
  set_fact:
    portal_repo_branch: "{{ port_git_branch.stdout }}"

- name: Set remote portal repo version (branch)
  set_fact:
    portal_repo_version: "{{ portal_repo_branch }}"
  when: (portal_repo_tag == '') and (portal_repo_branch != '')

- name: Get remote portal repo commit
  ansible.builtin.command:
    chdir: "{{ webportal_dir }}"
    cmd: git rev-parse --verify HEAD
  register: port_git_commit

- name: Set remote portal repo commit
  set_fact:
    portal_repo_commit: "{{ port_git_commit.stdout }}"

- name: Set remote portal repo version (commit)
  set_fact:
    portal_repo_version: "{{ portal_repo_commit }}"
  when: (portal_repo_tag == '') and (portal_repo_branch == '')
