---
# Get portal configs
# - Load portal configs from secrets backend (e.g. LastPass)
# - Set default values (for unset keys)
# - Set mongodb mgkey (if defined but empty)
# - Set mongodb flag
# - Set mongodb config (if mongodb is on)
# - Set accounts flag
# - Set blocker flag
# - Set abuse flag

- name: Include loading portal config
  include_tasks: "{{ playbook_dir }}/{{ load_portal_config_handler }}"

# If the server config hasn't been yet saved to secrets backend, it is loaded
# as undefined now and we set it to empty dictionary.
- name: Set portal config to empty (if it hasn't yet been saved to secrets backend)
  set_fact:
    webportal_server_config: "{{ webportal_server_config | default({}) }}"

- name: Set portal config missing variables to default values
  set_fact:
    webportal_server_config: "{{ webportal_server_config | combine({item.key: item.value}, recursive=True) }}"
  when: webportal_server_config[item.key] is not defined
  loop: "{{ webportal_server_config_defaults | dict2items }}"
  no_log: True

# If the common/cluster config hasn't been yet saved to secrets backend, it is
# loaded as undefined now and we set it to empty dictionary.
#
# This is also where we want to save a snapshot of the old version to compare
# against later.
- name: Set common/cluster config to empty (if it hasn't yet been saved to secrets backend)
  set_fact:
    webportal_common_config: "{{ webportal_common_config | default({}) }}"
    webportal_common_config_last: "{{ webportal_common_config_last | default({}) }}"
    webportal_common_config_last_old: "{{ webportal_common_config_last | default({}) }}"

- name: Set portal common/cluster config missing variables to default values to the last config
  set_fact:
    webportal_common_config_last: "{{ webportal_common_config_last | combine({item.key: item.value}, recursive=True) }}"
  when: webportal_common_config[item.key] is not defined
  loop: "{{ webportal_common_config_defaults | dict2items }}"
  no_log: True

- name: Merge missing key/value pairs to the common/cluster config
  set_fact:
    webportal_common_config: "{{ webportal_common_config | combine(webportal_common_config_last, recursive=True) }}"

# If the 'mgkey' key was not defined at all in any of common/cluster configs,
# the key/value pair with auto-generated value was added by above tasks, but if
# the 'mgkey' key was defined and the value is empty, undefined or null we set
# it now.
- name: Set default value for MongoDB mgkey (if the value is not set)
  set_fact:
    webportal_common_config_last: >-
      {{
        webportal_common_config_last
        | combine({'mongo_db_mgkey': webportal_common_config_defaults.mongo_db_mgkey})
      }}
  when: >-
    webportal_common_config.mongo_db_mgkey is none
    or webportal_common_config.mongo_db_mgkey | length == 0

# Get MongoDB config
# NOTE: Server config preference:
# Some MongoDB configuration can be set at common (cluster) level or at
# server level (e.g. db user, db password). For these we prefer server
# config over common (cluster) config.

- name: Set MongoDB config keys with preference of server config over common config
  set_fact:
    mongodb_config_keys_server_preference:
      - skynet_db_host
      - skynet_db_port
      # Other MongoDB keys (e.g. skynet_db_user/pass/replicaset) can't be set
      # on server level (different for each Mongo server) because they are
      # shared through the whole cluster/replicaset.

- name: Set MongoDB config with preference of server config over common config
  set_fact:
    mongodb_config: "{{ mongodb_config | default({}) | combine({item: webportal_server_config[item] | default(webportal_common_config[item]) }) }}"
  no_log: True
  ignore_errors: True
  register: mongodb_config_server_preference_result
  loop: "{{ mongodb_config_keys_server_preference }}"

# Fail if not ok
- name: Fail if there are missing MongoDB config items
  fail:
    msg: |
      Portal configuration error for MongoDB:

      For MongoDB you must configure all of the following items
      in server or common config:

      Items with server config preference (over common config):
      {% for key in mongodb_config_keys_server_preference %}
      - {{ key }}
      {% endfor %}
  failed_when: mongodb_config_server_preference_result.failed | default(False)

# If portal_modules is defined in hosts.ini, update the values
- name: Update portal_modules
  set_fact:
    webportal_server_config: "{{ webportal_server_config | combine({'portal_modules': portal_modules}, recursive=True) }}"
  when: portal_modules is defined

- name: Set Accounts flag
  set_fact:
    portal_accounts_on: >-
      {{ webportal_server_config.portal_modules is defined and
      webportal_server_config.portal_modules is not none and
      'a' in webportal_server_config.portal_modules }}

# Portal is anonymous if Accounts are off or if Accounts are on and
# accounts_limit_access is set to 'false' (case insensitive).
- name: Set portal is anonymous flag
  set_fact:
    portal_is_anonymous: >-
      {{ not portal_accounts_on
      or webportal_common_config.accounts_limit_access
      | default(False) | string | lower == 'false' }}

- name: Set Blocker flag
  set_fact:
    portal_blocker_on: >-
      {{ webportal_server_config.portal_modules is defined and
      webportal_server_config.portal_modules is not none and
      'b' in webportal_server_config.portal_modules }}

- name: Set Abuse Scanner flag
  set_fact:
    portal_abuse_scanner_on: >-
      {{ webportal_server_config.portal_modules is defined and
      webportal_server_config.portal_modules is not none and
      'u' in webportal_server_config.portal_modules }}

- name: Set Jaeger flag
  set_fact:
    portal_jaeger_on: >-
      {{ webportal_server_config.portal_modules is defined and
      webportal_server_config.portal_modules is not none and
      'j' in webportal_server_config.portal_modules }}

- name: Set Pinner flag
  set_fact:
    portal_pinner_on: >-
      {{ webportal_server_config.portal_modules is defined and
      webportal_server_config.portal_modules is not none and
      'p' in webportal_server_config.portal_modules }}
