---

# Ensure MongoDB replicaset is setup
# TODO: This ansible playbook task, should be moved to portal role

- name: Include getting MongoDB replicaset status
  include_tasks: tasks/portal-role-task-mongo-replicaset-get-status.yml
  # If the playbook is run against several hosts, setup replicaset only once
  # (on the first host of a batch)
  run_once: True

- name: Include setting MongoDB replicaset
  include_tasks: tasks/portal-role-task-mongo-replicaset-setup-subtask.yml
  when: not mongo_replicaset_online
  # If the playbook is run against several hosts, setup replicaset only once
  # (on the first host of a batch)
  run_once: True
