---

# Setup portal ufw firewall rules

- name: Install ufw firewall
  apt:
    name: ufw
    state: latest
    update_cache: True

- block:
    - name: Reset ufw (reset ufw rules and disables ufw firewall)
      community.general.ufw:
        state: reset
    
    - name: Limit SSH access
      community.general.ufw:
        rule: limit
        direction: in
        port: "{{ default_ssh_port | string }}"
        proto: tcp

    - name: Allow outgoing traffic by default
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: Deny incoming traffic by default
      community.general.ufw:
        default: deny
        direction: incoming

    - name: Load private variables from Ansible private repository
      ansible.builtin.include_vars:
        file: "{{ private_vars_file }}"
        name: private_vars
      delegate_to: localhost
    
    - name: Deny malicious traffic from ip ranges
      community.general.ufw:
        rule: "deny"
        proto: "any"
        direction: "in"
        from_ip: "{{ item }}"
      loop: "{{ private_vars.malicious_ip_ranges_denied }}"

    - name: Allow specific incoming ports
      community.general.ufw:
        rule: allow
        direction: in
        port: "'{{ item }}'"
        proto: tcp
      loop:
        - 80
        - 443
        - 26257
        - 27017

    - name: Allow outgoing traffic to docker local network
      community.general.ufw:
        rule: "allow"
        proto: "any"
        direction: "out"
        to_ip: "{{ item }}"
      loop: "{{ local_networks_allowed }}"      

    - name: Deny outgoing traffic to local networks
      community.general.ufw:
        rule: "deny"
        proto: "any"
        direction: "out"
        to_ip: "{{ item }}"
      loop: "{{ local_networks_denied }}"

  # On error set at least SSH rule and enable firewall
  always:
    - name: Limit SSH access
      community.general.ufw:
        rule: limit
        direction: in
        port: "{{ default_ssh_port | string }}"
        proto: tcp
    
    - name: Enable Firewall
      community.general.ufw:
        state: enabled
