---
# Get portal status

- name: Get versions files
  block:
    - name: Include getting portal, skyd, accounts versions
      include_tasks: tasks/portal-versions-get.yml
  rescue:
    - name: Getting versions failed but continue
      fail:
      failed_when: false

- name: Get modified files
  block:
    - name: Include checking for modified files after last Ansible docker services start
      include_tasks: tasks/portal-repo-get-modified-files.yml
  rescue:
    - name: Checking modified files failed but continue
      fail:
      failed_when: false

- name: Get portal status
  block:
    - name: Run health checks
      include_tasks: tasks/portal-health-checks-run.yml
  rescue:
    - name: Recover if health checks failed and set health checks flag
      set_fact:
        health_checks_failed: True
  # Exclude running health checks when they have already run
  when: portal_action == 'portal-get-status'

- name: Create json report data
  set_fact:
    portals_report_embeds: "{{ lookup('template', 'templates/portals-status.json.j2') }}"
