---

# Prepeare server for portal setup

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-pip
    - git
  become: True

- name: Include role to install Docker
  include_role:
    name: geerlingguy.docker
    apply:
      become: True

- name: Reset SSH connection to reload new user groups (docker)
  ansible.builtin.meta:
    reset_connection

- name: Install required Python modules
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-compose
    - pexpect

- name: Set timezone
  community.general.timezone:
    name: "{{ webportal_server_timezone }}"
  become: True
  when: webportal_server_set_timezone | default(False)

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: True
