---
# Prompt subtask to be throttled
# TODO: This ansible playbook task, should be moved to portal role

- name: Ask user if it is ok to delete and reset MongoDB database
  pause:
    prompt: |-
      Your MongoDB database doesn't run as expected.

      If you do not have any data in your database
      it is safe to continue.
      Your MongoDB database will be backupped to
      {{ mongo_backups_dir }}, deleted and reset.

      If you have production data in your database
      you should fix this issue manually and rerun this playbook.

      Do you want to reset MongoDB database on {{ inventory_hostname }} (y/n)?
  register: reset_db_result
  # If mongo/db directory doesn't exist we can skip this prompt.
  when: mongo_db_stat_result.stat.exists
  delegate_to: localhost

- name: Stop the playbook if the user doesn't want to delete and reset MongoDB database
  fail:
    msg: |
      Your MongoDB database doesn't run as expected,
      you have to fix it manually and then rerun this playbook.
  # If mongo/db directory doesn't exist the prompt was skipped, we need to
  # skip this task, otherwise we fail the playbook if the user doesn't want
  # to reset the mongo db.
  when: >-
    mongo_db_stat_result.stat.exists
    and
    reset_db_result.user_input[:1] not in 'yY'
