--- 

# Get portal accounts version

- name: Read docker-compose.accounts.yml
  slurp:
    src: "{{ webportal_dir }}/docker-compose.accounts.yml"
  register: docoaccounts

- name: Parse docker-compose.accounts.yml
  set_fact:
    docker_compose_accounts: "{{ docoaccounts['content'] | b64decode | from_yaml }}"

- name: Check accounts branch is defined in docker-compose.accounts.yml
  set_fact:
    accounts_branch_defined: "{{ docker_compose_accounts.services.accounts.build.args.branch is defined }}"

- name: Get accounts version (from docker-compose.accounts.yml)
  set_fact:
    portal_accounts_version_used: "{{ docker_compose_accounts.services.accounts.build.args.branch }}"
  when: accounts_branch_defined

- name: Get accounts version (from accounts/Dockerfile)
  block:
    
    - name: Read accounts/Dockerfile
      slurp:
        src: "{{ webportal_dir }}/docker/accounts/Dockerfile"
      register: dofiaccounts
    
    - name: Extract branch
      set_fact:
        portal_accounts_version_used: "{{ dofiaccounts['content'] | b64decode | regex_findall('RUN .* --branch (.*?) ') | first }}"
    

  when: not accounts_branch_defined