---
# Deploy Portal to Server Part 2: Run Tests and Enable Loadbalancer

- name: Include running portal integration tests
  include_tasks: tasks/portal-integration-tests-run.yml

- name: Include running portal health checks
  include_tasks: tasks/portal-health-checks-run.yml

- name: Include Updating the Allowance
  include_tasks: tasks/portal-update-allowance.yml
  # Only execute allowance check if portal is manually defined
  when: update_allowance is defined and inventory_hostname in update_allowance

- name: Update log status to 'tested'
  include_tasks: tasks/portal-logs-update-status.yml
  vars:
    tag_from: "started"
    tag_to: "tested"

- name: Include enabling portal health check
  # Do not enable health checks on hosts from out_of_LB group
  include_tasks: tasks/portal-health-check-enable.yml
  when: ('out_of_LB' not in group_names)

- name: Include getting portal status
  include_tasks: tasks/portal-status-get-status.yml

- name: Include reporting portal status to Discord
  include_tasks: tasks/portal-status-report-to-discord.yml
