---

# Set skynet-webportal versions

- name: Set portal version (checkout skynet-webportal repo version)
  ansible.builtin.git:
    repo: "{{ webportal_repo_url }}"
    dest: "{{ webportal_dir }}"
    version: "{{ portal_repo_version }}"
    update: True
    force: True

# Include getting current skyd and accounts versions from
# docker-compose.override.yml
- name: Include getting current skyd and accounts versions from docker-compose.override.yml
  include_tasks: tasks/portal-versions-get-skyd-accounts-versions.yml

# Set skyd version in docker-compose.override.yml
- name: Set skyd version in docker-compose.override.yml
  ansible.builtin.replace:
    path: "{{ webportal_dir }}/docker-compose.override.yml"
    after: "\n  sia:\n"
    before: "(?<=branch: {{ portal_skyd_version_used }}).*$"
    regexp: "^        branch: {{ portal_skyd_version_used }}"
    replace: "        branch: {{ portal_skyd_version }}"

# Set accounts version in docker-compose.override.yml
- name: Set accounts version in docker-compose.override.yml
  ansible.builtin.replace:
    path: "{{ webportal_dir }}/docker-compose.override.yml"
    after: "\n  accounts:\n"
    before: "(?<=branch: {{ portal_accounts_version_used }}).*$"
    regexp: "^        branch: {{ portal_accounts_version_used }}"
    replace: "        branch: {{ portal_accounts_version }}"