---
# Setup MongoDB replicaset
# TODO: This ansible playbook task, should be moved to portal role

- name: Include checking MongoDB node is a voting member
  include_tasks: tasks/portal-role-task-mongo-shell-eval.yml
  vars:
    mongodb_shell:
      eval: |
        rs.config().members.forEach(m => {
          if (m.host == '{{ ansible_host }}:{{ subcrap_mongo_port | default(default_mongo_port | string) }}' && m.votes > 0 )
          {
            print('is-voting')
          }
        })
      until: True
      retries: 0

- name: Voting member debug
  debug:
    msg: "Is voting: {{ mongo_shell_result.transformed_output == 'is-voting' }}"

- name: End play
  meta: end_play
