---
# Execute any defined shell command(s).
# This loops over all the shell commands listed and executes them one at a
# time.
- name: Executing shell command(s)
  ansible.builtin.shell: "{{ item }}"
  loop: "{{ shell_commands }}"
  when: shell_commands is defined

# Block any defined hosts
- name: Block any bad hosts
  ansible.builtin.command: "docker exec sia siac hostdb block {{ item }}"
  loop: "{{ hostdb_blocked_domains }}"
  when: hostdb_blocked_domains is defined

# Unblock any defined hosts
- name: Unblock hosts
  ansible.builtin.command: "docker exec sia siac hostdb unblock {{ item }}"
  loop: "{{ hostdb_unblock_domains }}"
  when: hostdb_unblock_domains is defined
