---
# Initialize MongoDB replicaset
# TODO: This ansible playbook task, should be moved to portal role

# Prompt if to continue if some mongo containers are not online
- block:
    - name: Ask user if it is ok to setup MongoDB replicaset
      ansible.builtin.pause:
        prompt: |-
          MongoDB replicaset (i.e. cluster setup) was not found on any cluster
          mongo container that is running, however there are some portal hosts
          or mongo containers from this cluster offline and you may already
          initialized MongoDB replicaset on them.

          Offline or not ok host(s)/container(s):
          {% for h in mongo_not_ok_host_list %}
          - {{ h }}
          {% endfor %}

          If you have already setup MongoDB replicaset on other host,
          do not setup another replicaset now,
          bring the offline hosts online first.

          Are you sure you want to setup a new MongoDB replicaset?
          (y/n)
      register: setup_mongo_replicaset_result
      delegate_to: localhost

    - name: Stop the playbook if the user doesn't want to setup new MongoDB replicaset
      meta: end_play
      when: setup_mongo_replicaset_result.user_input[:1].lower() != 'y'
  when: mongo_not_ok_host_list | length > 0

- name: Include MongoDB replicaset initialization
  include_tasks: tasks/portal-role-task-mongo-shell-eval.yml
  vars:
    mongodb_shell:
      # host value below must be in single quotes otherwise we get: SyntaxError: missing } after property list
      eval: |
        rs.initiate({
          _id : '{{ webportal_common_config.skynet_db_replicaset }}',
          members: [{_id: 0, host: '{{ ansible_host }}:{{ custom_mongo_port | default(default_mongo_port | string) }}'}]
        })
      until: True
      retries: 0
  register: mongo_initialize_replicaset_result

- name: Fail if MongoDB replicaset initialization was not successful
  fail:
    msg: |
      MongoDB replicaset initialization was not successful:

      Mongo shell result: {{ mongo_shell_result }}
  when: "mongo_shell_result.transformed_output | default('none output') != '{ \"ok\" : 1 }'"

- name: Set MongoDB initialized flag
  ansible.builtin.set_fact:
    mongo_replicaset_initialized: True
