---

# TODO: Move this task to skynet_webportal role > mongo task, include it
# only if accounts are on

# Ensure that mgkey file exists:
# - random string for non cluster host
# - common config.mongo_db_mgkey for cluster host
# mgkey is used for cluster setup, but we need mgkey even for non-cluster setup
# otherwise mongo container will not run correctly.

- name: Remove mongo and mongo-test containers (if exist)
  docker_container:
    name: "{{ item }}"
    state: absent
    container_default_behavior: no_defaults
  loop:
    - mongo
    - mongo-setup

- name: Ensure mgkey parent directory exists
  ansible.builtin.file:
    path: "{{ webportal_docker_data_mongo_dir }}"
    state: directory
  become: True

- name: Remove mgkey file/dir if exists
  ansible.builtin.file:
    path: "{{ webportal_mongo_db_mgkey_file }}"
    state: absent
  become: True

- name: Ensure mgkey with content file exists
  ansible.builtin.copy:
    content: "{{ webportal_common_config.mongo_db_mgkey if (portal_cluster_id is defined) else lookup('community.general.random_string', base64=True, length=756) }}"
    dest: "{{ webportal_mongo_db_mgkey_file }}"
    owner: "999"
    group: "999"
    mode: "0400"
  become: True

- name: Include setting up MongoDB cluster (if portal is in cluster)
  include_tasks: tasks/portal-role-task-mongo-cluster.yml
  when: portal_cluster_id is defined
