---

# Clean Portal sia/renter/renter.log file

# Note: This task should be performed while sia is stopped

- name: Pull Alpine image
  community.docker.docker_image:
    name: alpine:3.15.0
    source: pull

# Running sed command using community.docker.docker_container module didn't
# work correctly, using ansible.builtin.command instead
- name: Clean renter.log file
  ansible.builtin.command: "docker run -v {{ webportal_dir }}/docker/data/sia/renter:/sia-renter --name clean-renter-log alpine:3.15.0 sed -i '/pt not ready yet for worker/d' /sia-renter/renter.log"
