---
# Save secret data to yaml or json record in secrets storage

- name: Set secret path extension
  set_fact:
    secret_path_extension: "{{ secret_path.split('.') | last }}"

- name: Assert secret data was passed correctly
  ansible.builtin.assert:
    that:
      - secret_path is defined
      - secret_path != ''
      - secret_path_extension == 'yml' or secret_path_extension == 'json'
      - secret_data is defined
      - secret_data != 'undefined'

# We need to format json data to string at the time of saving as it is loaded
# back as data (not json string) on each Ansible assignment.
- name: Set secret string to format according to secret path extension
  set_fact:
    secret_string_formatted: >-
      {{
        secret_data | to_nice_yaml(width=2048)
        if secret_path_extension == 'yml'
        else secret_data
      }}

- name: Include saving secret string to secrets storage
  include_tasks: "tasks/secrets-storage-common-save-string-to-yaml-or-json.yml"
  vars:
    save_string_secret_path: "{{ secret_path }}"
    secret_string: "{{ secret_string_formatted }}"

- name: Reset passed secret path and data
  set_fact:
    secret_path: ''
    secret_data: 'undefined'
