---
# Check if secret exists in HashiCorp Vault

- name: Check if HashiCorp server record exists
  community.hashi_vault.vault_read:
    url: "{{ lookup('env', 'HCV_URL') }}"
    path: "{{ hashicorp_vault_storage_backend_dir }}/{{ secret_path }}"
    token: "{{ lookup('env', 'HCV_TOKEN') }}"
  delegate_to: localhost
  changed_when: False
  failed_when: False
  register: hashicorp_vault_get_secret_result

- name: Set secret exists flag
  set_fact:
    secrets_storage_record_exists: "{{ hashicorp_vault_get_secret_result.data is defined }}"
