---
# Save secret string to yaml or json record in secrets storage

- name: Assert secret string was passed correctly
  ansible.builtin.assert:
    that:
      - secret_path is defined
      - secret_path != ''
      - secret_string is defined
      - secret_string != 'undefined'

- name: Include saving string yo yaml to secure storage
  include_tasks: "tasks/secrets-storage-{{ secrets_storage }}-save-string-to-yaml-or-json.yml"

- name: Reset passed secret path and data
  set_fact:
    secret_path: ''
    secret_string: 'undefined'
