---
# Save secret data to yaml record in secrets storage

- name: Assert secret data was passed correctly
  ansible.builtin.assert:
    that:
      - secret_path is defined
      - secret_path != ''
      - secret_data is defined
      - secret_data != 'undefined'

- name: Include saving secret string to secrets storage
  include_tasks: "tasks/secrets-storage-common-save-string-to-yaml.yml"
  vars:
    secret_path: "{{ server_config_secret_path }}"
    secret_string: "{{ secret_data | to_nice_yaml(width=2048) }}"

- name: Reset passed secret path and data
  set_fact:
    secret_path: ''
    secret_data: 'undefined'
