---
# Run shell commands one at a time defined in `shell_commands` variable.

- name: Assert that user defined `shell_commands` variable
  ansible.builtin.assert:
    that:
      - shell_commands is defined
      - shell_commands | type_debug == "list"
    fail_msg: |
      Configuration error:
      Variable shell_commands must be defined as a list of commands to be run.
      shell_commands is defined: {{ shell_commands is defined }}
      {% if shell_commands is defined %}
      shell_commands is list: {{ shell_commands | type_debug == "list" }}
      {% endif %}

- name: Include running and logging output of a single command
  include_tasks: tasks/shell-commands-run-subtask.yml
  loop: "{{ shell_commands }}"
