# This config file can be used to set any ansible variables needed to execute
# necessary ansible playbooks. These settings when used will also override
# values defined in playbooks/group_vars/webportals.yml.

###############################################################################
# REQUIRED
#
# Below are a list of variables that require attention if the defaults are not
# suitable.
###############################################################################

###############################################################################
# Server Setup
#
# Below are some of the recommended server level settings for portals. If you
# wish to disable any of these settings, uncomment the variable and change the
# value.
# 
# PLEASE NOTE: We have not tested any non-default conditions for these
# settings, so you should be comfortable debugging the server and portal on
# your own if you plan to change these settings. 
#
# Setup basic security (default: True)
# Creates sudo users, adds SSH keys, executes geerlingguy.security Ansible
# role (secures SSH etc.).
# setup_basic_security: True
#
# Enable fail2ban (default: True)
# Requires: setup_basic_security: True
# Fail2ban is a security tool to protect servers from brute-force attacks for
# various services, e.g. SSH.
# security_fail2ban_enabled: True
#
# Set server timezone (default: True)
# Based on your system, e.g. UTC timezone should be set as "UTC" or "Etc/UTC"
# webportal_server_set_timezone: True
# webportal_server_timezone: "UTC"
#
# Update server hostname (default: True)
# The script will update server hostname to Ansible inventory_hostname as
# defined in your inventory/hosts.ini (to e.g.: "skynet-node-01")
# webportal_update_hostname: True
#
# Setup UFW firewall (default: True)
# setup_ufw: True
#
# Deny outgoing traffic to local networks via UFW (default: True)
# Requires: setup_ufw: True
# Some services used to scan local networks, so according to server providers'
# advice operators can disable outgoing traffic to local networks. This might
# disrupt existing services (other than skynet portal stack) on the server.
# ufw_deny_outgoing_to_local_network: True


###############################################################################
# LastPass
#
# LastPass is used for managing secrets with ansible, such as server config
# files and login information.
#
# lastpass_ansible_dir is the folder name in lastpass that contains server login
# information. The default is `Shared-Ansible`. You can either create this
# folder in LastPass or rename this variable to the folder name you desired.
#
# NOTE: If you rename this variable, you should keep this variable defined in
# this config file for any ansible playbook you use. Otherwise, if you keep the
# defaults you can safely remove these from the config file.
lastpass_ansible_dir: "Shared-Ansible"
# The Following are the subfolder names of the lastpass_ansible_dir folder in
# lastpass. The contents of these folders are controlled by ansible. Below are
# the defaul values. You can either create these folders in LastPass or rename
# these variable to the folder name you desired.
#
# NOTE: If you rename these variables, you should keep these variables defined
# in this config file for any ansible playbook you use. Otherwise, if you keep
# the defaults you can safely remove these from the config file.
lastpass_portal_credentials_server_subfolder: "portal-server-credentials"
lastpass_portal_config_common_subfolder: "portal-common-configs"
lastpass_portal_config_cluster_subfolder: "portal-cluster-configs"
# Common config is optional. It is useful if you run several clusters and want
# to extract some common values from multiple cluster configs to a common
# config. Otherwise you can use just one or several cluster configs.
# Operators with a single cluster will use just one cluster-{...}.yaml in the
# list. Operators with multiple clusters (e.g. dev and prod clusters or e.g.
# paid-only prod1 and allow-anonymous access prod2 clusters) will have several
# cluster-{...}.yml which is still covered with the dafault configs list. They
# have however option to extract common, shared values for all clusters from
# multiple cluster-{...}.yml configs to a common.yml. If a setting is present
# in several levels (both common and cluster) the setting in earlier config in
# the list (common.yml) is overriden with later config in the list
# (cluster-{...}.yml).
lastpass_portal_common_and_cluster_configs_list:
  # - "{{ lastpass_ansible_dir }}/{{ lastpass_portal_config_common_subfolder }}/common.yml"
  - "{{ lastpass_ansible_dir }}/{{ lastpass_portal_config_cluster_subfolder }}/cluster-{{ portal_cluster_id }}.yml"
lastpass_portal_config_server_subfolder: "portal-server-configs"

###############################################################################
# SSH Access
#
# During portals-setup-following, ansible can add a list of authorized pubkeys
# to your server. This is helpful if you are planning on managing a server with
# a team. Ansible is set up to pull this list from a url, like a github repo. If
# you leave the variable blank, no additional keys will be added.
#
# Example
# webportal_user_authorized_keys: "https://raw.githubusercontent.com/SkynetLabs/skynet-webportal/master/setup-scripts/support/authorized_keys"
webportal_user_authorized_keys: ""

###############################################################################
# Emails
#
# There are two places emails are required. One is for ssl certificate
# generation and one is for git checkout commands.
#
# The ssl_support_email can be whatever email you would like.
#
# The git_checkout_email should be the email associated with your Github
# account.
ssl_support_email: ""
git_checkout_email: ""

###############################################################################
# OPTIONAL
#
# Below are a list of variables that are optional depending on the playbook you
# are running.
###############################################################################

# Set the skynet-webportal, skyd, and accounts versions by entering a git
# branch, git tag or git commit.
portal_repo_version: "..."
portal_skyd_version: "..."
portal_accounts_version: "..."
