# Name your playbook, this is printed in STDOUT
- name: My Cool Playbook
  # Define your target hosts, this typically doesn't change
  hosts: webportals
  # Define the user that is executing the commands, this typically doesn't
  # change
  remote_user: "{{ webportal_user }}"
  # Tell ansible if it should gather information about the hosts. This is
  # currently only used in setting up the servers.
  gather_facts: False

  # Limit concurrency or the playbook if needed
  serial: 1

  # Execute playbook on hosts in parallel as fast as possible (do not wait for other hosts)
  # strategy: free

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"

  # Define the tasks for your playbook
  tasks:
    - name: Hello World
      ansible.builtin.command: echo "Hello World"

    # Example of calling a refactored task
    - name: Run my refactored task
      include_tasks: tasks/my-factored-task.yml

    # Example of task with additional vars
    - name: My task with vars
      include_tasks: tasks/my-task-with-vars.yml
      vars:
        foo: "this can be used in my-task-with-vars.yml as 'bar'"
        bar: "this can be used in my-task-with-vars.yml as 'bar'"

    # Example of task with 'when' condition
    - name: Only execute when something is true
      # do not enable health checks on hosts from out_of_LB group
      when: some_variable is defined
      include_tasks: tasks/excute-when-condition-is-true.yml
