---

- name: Demo serial execution 
  hosts: webportals
  gather_facts: False
  serial: 1
  vars_files:
    - vars/common.yml
  vars:
    max_hosts: "{{ groups['webportals'] | length }}"

  tasks:

    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    - name: Stat skynet-webportal dir
      stat:
        path: "{{ webportal_dir }}"
      register: wds
    
    - name: Fail if skynet-webportal dir is not present
      fail:
        msg: "skynet-webportal dir is not present"
      when: wds.stat.isdir is not defined or not wds.stat.isdir