- name: Setup Portals Deploy Machine
  hosts: deploy_machines
  gather_facts: True

  # Limit concurrency
  serial: 1

  # Load common vars
  vars_files:
  - vars/deploy-machines.yml

  roles:

    # Install Docker
    - role: geerlingguy.docker
      become: True

    # Secure the server
    - role: geerlingguy.security
      become: True
  
  tasks:

    # Check host OS version
    - name: Check supported OS and version
      assert:
        that:
          - ansible_distribution|lower == 'debian' and ansible_distribution_version == '10'
        fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not yet supported by this role"
    
    # Configure server
    - name: Run "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 900
      become: True

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      become: True
      loop:
        - sudo
        - python3-pip
        - lastpass-cli
    
    - name: Create lpass working dir
      ansible.builtin.file:
        path: "{{ item }}" 
        state: directory
      loop:
        - /home/user/.config/lpass
        - /home/user/.local/share/lpass

    - name: Install Docker SDK for Python
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - docker

    - name: Set timezone
      community.general.timezone:
        name: "UTC"
      become: True
    
    # Ensure configured user
    - name: Ensure configured user
      ansible.builtin.user:
        name: "user"
        groups:
          - sudo
          - docker
      become: True
    
    # Configure ufw firewall
    - name: Setup ufw firewall
      include_tasks: tasks/firewall-ufw-setup.yml
      args:
        apply:
          become: True
    
    # Checkout ansible-playbooks repo
    - name: Checkout ansible-playbooks repo
      ansible.builtin.git:
        repo: "https://github.com/SkynetLabs/ansible-playbooks.git"
        dest: "/home/user/ansible-playbooks"
  
  handlers:

    - name: reload ufw firewall
      community.general.ufw:
        state: reloaded
      become: True