---
# Setup and Secure dev achines
# This role is expected to be executed with root permissions

- name: Setup and Secure dev Machines
  hosts: dev_machines
  gather_facts: True

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  tasks:

    # Check host OS version
    - name: Check supported OS and version
      assert:
        that:
          - ansible_distribution|lower == 'debian' and ansible_distribution_version == '10'
        fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not yet supported by this role"
    
    # Update apt
    - name: Run "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 900
    
    # Install sudo
    - name: Install sudo
      apt:
        name: sudo
        state: present
    
    # Ensure docker group
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: "docker"
        state: present
    
    # Ensure configured users
    - name: Ensure configured user
      ansible.builtin.user:
        name: "{{ item }}"
        groups:
          - sudo
          - docker
      loop: "{{ users_to_add }}"
    
    # Add SSH authorized keys
    - name: Add SSH authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ item.key }}"
      loop: "{{ ssh_keys_to_add }}"
    
    # Secure server
    - name: Include role to secure server
      include_role:
        name: geerlingguy.security
    
    # Configure ufw firewall
    - name: Setup ufw firewall
      include_tasks: tasks/firewall-ufw-setup.yml
    
    # Install Docker
    - name: Include role to install Docker
      include_role:
        name: geerlingguy.docker

    # Set timezone
    - name: Set timezone
      community.general.timezone:
        name: "UTC"
  
  handlers:

    - name: reload ufw firewall
      community.general.ufw:
        state: reloaded
      become: True