- name: Create report of all servers
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False
  vars:
    max_hosts: 1

  tasks:
    - name: Request /renter
      ansible.builtin.uri:
        url: "http://10.10.10.10:9980/renter"
        http_agent: "Sia-Agent"
      register: renter_result

    - name: Request /skynet/stats
      ansible.builtin.uri:
        url: "http://10.10.10.10:9980/skynet/stats"
        http_agent: "Sia-Agent"
      register: stats_result

    - name: Extract variables
      ansible.builtin.set_fact:
        # Storage
        numfiles: "{{ stats_result.json.numfiles }}"
        storage: "{{ stats_result.json.storage }}"

        # Metrics
        basesectorupload15mp99ms: "{{ stats_result.json.basesectorupload15mp99ms }}"
        streambufferread15mp99ms: "{{ stats_result.json.streambufferread15mp99ms }}"
        registryread15mp99ms: "{{ stats_result.json.registryread15mp99ms }}"
        registrywrite15mp99ms: "{{ stats_result.json.registrywrite15mp99ms }}"
        
        # Spending
        storagespending: "{{ renter_result.json.financialmetrics.storagespending }}"
        uploadspending: "{{ renter_result.json.financialmetrics.uploadspending }}"
        downloadspending: "{{ renter_result.json.financialmetrics.downloadspending }}"
        fundaccountspending: "{{ renter_result.json.financialmetrics.fundaccountspending }}"
        contractfees: "{{ renter_result.json.financialmetrics.fees.contractfees }}"
        transactionfees: "{{ renter_result.json.financialmetrics.fees.transactionfees }}"
        accountbalancecost: "{{ renter_result.json.financialmetrics.maintenancespending.accountbalancecost }}"
        fundaccountcost: "{{ renter_result.json.financialmetrics.maintenancespending.fundaccountcost }}"
        updatepricetablecost: "{{ renter_result.json.financialmetrics.maintenancespending.updatepricetablecost }}"

        totalallocated: "{{ renter_result.json.financialmetrics.totalallocated }}"
        unspent: "{{ renter_result.json.financialmetrics.unspent }}"
        previousspending: "{{ renter_result.json.financialmetrics.previousspending }}"
      
    - name: Sum up TotalSpent
      ansible.builtin.set_fact:
        totalspent: "{{ storagespending | int + uploadspending | int + downloadspending | int + fundaccountspending | int + contractfees | int + transactionfees | int + accountbalancecost | int + fundaccountcost | int + updatepricetablecost | int }}"

    - name: Sum up UnspentAllocated
      ansible.builtin.set_fact:
        unspentallocated: "{{ totalallocated | int - totalspent | int }}"

    - name: Sum up UnspentUnallocated
      ansible.builtin.set_fact:
        unspentunallocated: "{{ unspent | int - unspentallocated | int }}"

    - name: Sum up EAs
      ansible.builtin.set_fact:
        downloadscost: "{{ downloadscost | default(0) | int + item.downloadscost | int }}"
        uploadscost: "{{ uploadscost | default(0) | int + item.uploadscost | int }}"
        registryreadscost: "{{ registryreadscost | default(0) | int + item.registryreadscost | int }}"
        registrywritescost: "{{ registrywritescost | default(0) | int + item.registrywritescost | int }}"
        repairdownloadscost: "{{ repairdownloadscost | default(0) | int + item.repairdownloadscost | int }}"
        repairuploadscost: "{{ repairuploadscost | default(0) | int + item.repairuploadscost | int }}"
        subscriptionscost: "{{ subscriptionscost | default(0) | int + item.subscriptionscost | int }}"
      with_items: "{{ renter_result.json.financialmetrics.ephemeralaccountspending }}"
        
    - name: Print per-server result
      debug:
        msg: |
          Aggregates:
            NumFiles: {{ numfiles }}
            Storage:  {{ storage }}

          Medians:
            BaseSectorUpload(p99): {{ basesectorupload15mp99ms }}
            StreamBufferRead(p99): {{ streambufferread15mp99ms }}
            RegistryRead(p99):     {{ registryread15mp99ms }}
            RegistryWrite(p99):    {{ registrywrite15mp99ms }}

          Averages:
            ContractSpending:
              Total Allocated:         {{ totalallocated }}
              Total Spent:             {{ totalspent }}
                Storage:               {{ storagespending }}
                Uploads:               {{ uploadspending }}
                Downloads:             {{ downloadspending }}
                FundAccount:           {{ fundaccountspending }}
                Fees:
                  Contracts:           {{ contractfees }}
                  Txns:                {{ transactionfees }}
                  Maintenance:
                    GetAccountBalance: {{ accountbalancecost }}
                    FundAccount:       {{ fundaccountcost }}
                    UpdatePriceTable:  {{ updatepricetablecost }}
              Unspent:                 {{ unspent }}
                Allocated:             {{ unspentallocated }}
                Unallocated:           {{ unspentunallocated }}
              PreviousSpending:        {{ previousspending }}

            EphemeralAccountSpending:
              Downloads:       {{ downloadscost }}
              Uploads:         {{ uploadscost }} (NOTE: still using legacy uploads)
              RegistryRead:    {{ registryreadscost }}
              RegistryWrite:   {{ registrywritescost }}
              RepairDownload:  {{ repairdownloadscost }}
              RepairUpload:    {{ repairuploadscost }} (NOTE: still using legacy uploads for repairs)
              Subscriptions:   {{ subscriptionscost }}

    - name: Aggregate over all servers
      set_fact:
        # TODO: finish this
      loop: "{{ ansible_play_hosts }}"
      run_once: True
      