- name: Get Skynet Webportals status
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Playbook specific vars
  vars:
    portal_action: "portal-get-status"

  tasks:
    - name: Include getting portal status
      include_tasks: tasks/portal-status-get-status.yml

- name: Report Skynet Webportals status to discord
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Limit concurrency to handle Discord webhook rate limits
  serial: 1

  tasks:
    - name: Include reporting status to Discord
      include_tasks: tasks/portal-status-report-to-discord.yml
