- name: Get Skynet Webportals versions
  hosts: webportals
  gather_facts: False

  # Load common vars
  vars_files:
  - vars/common.yml

  tasks:

    # Include getting portal, Sia, accounts versions
    - name: Include getting portal, Sia, accounts versions
      include_tasks: tasks/portal-versions-get.yml

    # Include checking for modified files after last Ansible docker services start
    - name: Include checking for modified files after last Ansible docker services start
      include_tasks: tasks/portal-repo-get-modified-files.yml