- name: Set vm.max_map_count on Skynet Webportals
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"
    lastpass_required: True
    vm_max_map_count: 262144
  vars_files:
    # Define as an array to handle undefined files. At least one file needs to
    # be defined otherwise there will be an error. common_vars_file is expected
    # to always be defined.
    - ["{{ common_vars_file }}", "{{ custom_vars_file  }}"]

  tasks:
    # Set vm.max_map_count directly
    - name: Set vm.max_map_count directly
      command: "sysctl -w vm.max_map_count={{ vm_max_map_count }}"
      become: True

    # Set vm.max_map_count in /etc/sysctl.conf
    - name: Set vm.max_map_count in /etc/sysctl.conf
      ansible.builtin.blockinfile:
        path: /etc/sysctl.conf
        block: "vm.max_map_count={{ vm_max_map_count }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK for ELK"
      become: True
