- name: Get Skynet Webportals versions
  hosts: webportals
  gather_facts: False

  # Load common vars
  vars_files:
  - vars/common.yml

  tasks:

    # Get versions files
    - block:

        # Include getting portal, Sia, accounts versions
        - name: Include getting portal, Sia, accounts versions
          include_tasks: tasks/portal-versions-get.yml
      
      rescue:

        - name: Getting versions failed but continue
          fail:
          failed_when: false
    
    # Get modified files
    - block:

        # Include checking for modified files after last Ansible docker services start
        - name: Include checking for modified files after last Ansible docker services start
          include_tasks: tasks/portal-repo-get-modified-files.yml
      
      rescue:

        - name: Checking modified files failed but continue
          fail:
          failed_when: false

    # # xxx
    # - name: List hosts
    #   template:
    #     src: templates/portals-status.json.j2
    #     dest: myhosts.json
    #   delegate_to: localhost
    #   run_once: True
    
    # Create json report data
    - name: Create json report string
      set_fact:
        portals_report_embeds: "{{ lookup('template', 'templates/portals-status.json.j2') }}"
      # delegate_to: localhost
      # run_once: True
    
    # Report versions and modified files to Discord
    - name: Report versions and modified files to Discord
      uri:
        url: "{{ discord_ansible_logs_webhook }}"
        method: 'POST'
        body_format: json
        headers:
          Content-Type: 'application/json'
        body: {
          'content': 'Ansible Get Status',
          'embeds': "{{ portals_report_embeds.embeds }}"
        }
        status_code: 204
      # delegate_to: localhost
      # run_once: True