- name: Prepare Skynet Webportals for our Ansible playbooks
  hosts: webportals
  gather_facts: False

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Load common vars
  vars_files:
  - vars/common.yml

  tasks:
    
    # Install python3-pip
    - name: Install python3-pip
      apt:
        name: "python3-pip"
        state: latest
    
    # Install Docker and docker-compose SDKs for Python
    - name: Install Docker and docker-compose SDKs for Python
      pip:
        name: "{{ item }}"
        state: latest
      loop:
        - "docker"
        - "docker-compose"
    
    # Create devops/logs dir to log activity
    - name: Create devops/logs directory
      ansible.builtin.file:
        path: "{{ logs_dir }}"
        state: directory
        owner: "user"
        group: "user"
        mode: '0700'