- name: Block and unblock incoming traffic to Skynet Portal
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Set parallel concurrency, 'free' means hosts do not wait for each other.
  strategy: free

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"
    lastpass_required: True

  tasks:
    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    - name: Ping to filter out unreachable hosts
      ansible.builtin.ping:
    
    - name: Include blocking and unblocking incoming traffic to portal
      include_tasks: tasks/portal-firewall-iptables-block-unblock.yml
      args:
        apply:
          become: True
