- name: Create report of all servers
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False
  vars:
    max_hosts: 1

  tasks:
    - name: Request /renter
      ansible.builtin.uri:
        url: "http://10.10.10.10:9980/renter"
        http_agent: "Sia-Agent"
      register: renter_result

    - name: Request /skynet/stats
      ansible.builtin.uri:
        url: "http://10.10.10.10:9980/skynet/stats"
        http_agent: "Sia-Agent"
      register: stats_result

    - name: Extract variables
      ansible.builtin.set_fact:
        # Storage
        numfiles: "{{ stats_result.json.numfiles }}"
        storage: "{{ stats_result.json.storage }}"

        # Metrics
        basesectorupload15mp99ms: "{{ stats_result.json.basesectorupload15mp99ms }}"
        streambufferread15mp99ms: "{{ stats_result.json.streambufferread15mp99ms }}"
        registryread15mp99ms: "{{ stats_result.json.registryread15mp99ms }}"
        registrywrite15mp99ms: "{{ stats_result.json.registrywrite15mp99ms }}"
        
        # Spending
        storagespending: "{{ renter_result.json.financialmetrics.storagespending }}"
        uploadspending: "{{ renter_result.json.financialmetrics.uploadspending }}"
        downloadspending: "{{ renter_result.json.financialmetrics.downloadspending }}"
        fundaccountspending: "{{ renter_result.json.financialmetrics.fundaccountspending }}"
        contractfees: "{{ renter_result.json.financialmetrics.fees.contractfees }}"
        transactionfees: "{{ renter_result.json.financialmetrics.fees.transactionfees }}"
        accountbalancecost: "{{ renter_result.json.financialmetrics.maintenancespending.accountbalancecost }}"
        fundaccountcost: "{{ renter_result.json.financialmetrics.maintenancespending.fundaccountcost }}"
        updatepricetablecost: "{{ renter_result.json.financialmetrics.maintenancespending.updatepricetablecost }}"

        totalallocated: "{{ renter_result.json.financialmetrics.totalallocated }}"
        unspent: "{{ renter_result.json.financialmetrics.unspent }}"
        previousspending: "{{ renter_result.json.financialmetrics.previousspending }}"
      
    - name: Sum up TotalSpent
      ansible.builtin.set_fact:
        totalspent: "{{ storagespending | int + uploadspending | int + downloadspending | int + fundaccountspending | int + contractfees | int + transactionfees | int + accountbalancecost | int + fundaccountcost | int + updatepricetablecost | int }}"

    - name: Sum up UnspentAllocated
      ansible.builtin.set_fact:
        unspentallocated: "{{ totalallocated | int - totalspent | int }}"

    - name: Sum up UnspentUnallocated
      ansible.builtin.set_fact:
        unspentunallocated: "{{ unspent | int - unspentallocated | int }}"

    - name: Sum up EAs
      ansible.builtin.set_fact:
        downloadscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='downloadscost') | map('int') | sum }}"
        uploadscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='uploadscost') | map('int') | sum }}"
        registryreadscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='registryreadscost') | map('int') | sum }}"
        registrywritescost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='registrywritescost') | map('int') | sum }}"
        repairdownloadscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='repairdownloadscost') | map('int') | sum }}"
        repairuploadscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='repairuploadscost') | map('int') | sum }}"
        subscriptionscost: "{{ renter_result.json.financialmetrics.ephemeralaccountspending | map(attribute='subscriptionscost') | map('int') | sum }}"
        
    - name: Print per-server result
      debug:
        msg: |
          Aggregates:
            NumFiles: {{ numfiles }}
            Storage:  {{ storage }}

          Medians:
            BaseSectorUpload(p99): {{ basesectorupload15mp99ms }}
            StreamBufferRead(p99): {{ streambufferread15mp99ms }}
            RegistryRead(p99):     {{ registryread15mp99ms }}
            RegistryWrite(p99):    {{ registrywrite15mp99ms }}

          Averages:
            ContractSpending:
              Total Allocated:         {{ totalallocated }}
              Total Spent:             {{ totalspent }}
                Storage:               {{ storagespending }}
                Uploads:               {{ uploadspending }}
                Downloads:             {{ downloadspending }}
                FundAccount:           {{ fundaccountspending }}
                Fees:
                  Contracts:           {{ contractfees }}
                  Txns:                {{ transactionfees }}
                  Maintenance:
                    GetAccountBalance: {{ accountbalancecost }}
                    FundAccount:       {{ fundaccountcost }}
                    UpdatePriceTable:  {{ updatepricetablecost }}
              Unspent:                 {{ unspent }}
                Allocated:             {{ unspentallocated }}
                Unallocated:           {{ unspentunallocated }}
              PreviousSpending:        {{ previousspending }}

            EphemeralAccountSpending:
              Downloads:       {{ downloadscost }}
              Uploads:         {{ uploadscost }} (NOTE: still using legacy uploads)
              RegistryRead:    {{ registryreadscost }}
              RegistryWrite:   {{ registrywritescost }}
              RepairDownload:  {{ repairdownloadscost }}
              RepairUpload:    {{ repairuploadscost }} (NOTE: still using legacy uploads for repairs)
              Subscriptions:   {{ subscriptionscost }}

    - name: Sum over all servers
      set_fact:
        sumnumfiles: "{{ sumnumfiles | default(0) | int + hostvars[item].numfiles | int }}"
        sumstorage: "{{ sumstorage | default(0) | int + hostvars[item].storage | int }}"
        sumstoragespending: "{{ sumstoragespending | default(0) | int + hostvars[item].storagespending | int }}"
        sumuploadspending: "{{ sumuploadspending | default(0) | int + hostvars[item].uploadspending | int }}"
        sumdownloadspending: "{{ sumdownloadspending | default(0) | int + hostvars[item].downloadspending | int }}"
        sumfundaccountspending: "{{ sumfundaccountspending | default(0) | int + hostvars[item].fundaccountspending | int }}"
        sumcontractfees: "{{ sumcontractfees | default(0) | int + hostvars[item].contractfees | int }}"
        sumtransactionfees: "{{ sumtransactionfees | default(0) | int + hostvars[item].transactionfees | int }}"
        sumaccountbalancecost: "{{ sumaccountbalancecost | default(0) | int + hostvars[item].accountbalancecost | int }}"
        sumfundaccountcost: "{{ sumfundaccountcost | default(0) | int + hostvars[item].fundaccountcost | int }}"
        sumupdatepricetablecost: "{{ sumupdatepricetablecost | default(0) | int + hostvars[item].updatepricetablecost | int }}"
        sumtotalallocated: "{{ sumtotalallocated | default(0) | int + hostvars[item].totalallocated | int }}"
        sumunspent: "{{ sumunspent | default(0) | int + hostvars[item].unspent | int }}"
        sumpreviousspending: "{{ sumpreviousspending | default(0) | int + hostvars[item].previousspending | int }}"
        sumtotalspent: "{{ sumtotalspent | default(0) | int + hostvars[item].totalspent | int }}"
        sumunspentallocated: "{{ sumunspentallocated | default(0) | int + hostvars[item].unspentallocated | int }}"
        sumunspentunallocated: "{{ sumunspentunallocated | default(0) | int + hostvars[item].unspentunallocated | int }}"
        sumdownloadscost: "{{ sumdownloadscost | default(0) | int + hostvars[item].downloadscost | int }}"
        sumuploadscost: "{{ sumuploadscost | default(0) | int + hostvars[item].uploadscost | int }}"
        sumregistryreadscost: "{{ sumregistryreadscost | default(0) | int + hostvars[item].registryreadscost | int }}"
        sumregistrywritescost: "{{ sumregistrywritescost | default(0) | int + hostvars[item].registrywritescost | int }}"
        sumrepairdownloadscost: "{{ sumrepairdownloadscost | default(0) | int + hostvars[item].repairdownloadscost | int }}"
        sumrepairuploadscost: "{{ sumrepairuploadscost | default(0) | int + hostvars[item].repairuploadscost | int }}"
        sumsubscriptionscost: "{{ sumsubscriptionscost | default(0) | int + hostvars[item].subscriptionscost | int }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: True

    - name: Create lists for p99 values
      set_fact:
        basesectorupload15mp99mslist: []
        streambufferread15mp99mslist: []
        registryread15mp99mslist: []
        registrywrite15mp99mslist: []

    - name: Add elements to p99 lists
      set_fact:
        basesectorupload15mp99mslist: "{{ basesectorupload15mp99mslist + [ hostvars[item].basesectorupload15mp99ms | int ] }}"
        streambufferread15mp99mslist: "{{ streambufferread15mp99mslist + [ hostvars[item].streambufferread15mp99ms | int ] }}"
        registryread15mp99mslist: "{{ registryread15mp99mslist + [ hostvars[item].registryread15mp99ms | int ] }}"
        registrywrite15mp99mslist: "{{ registrywrite15mp99mslist + [ hostvars[item].registrywrite15mp99ms | int ] }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: True

    - name: Sort lists of p99 values
      set_fact:
        basesectorupload15mp99mslist: "{{ basesectorupload15mp99mslist | sort}}"
        streambufferread15mp99mslist: "{{ streambufferread15mp99mslist | sort}}"
        registryread15mp99mslist: "{{ registryread15mp99mslist | sort}}"
        registrywrite15mp99mslist: "{{ registrywrite15mp99mslist | sort}}"

    - name: Aggregate over all servers
      set_fact:
        # Medians
        medianbasesectorupload15mp99ms: "{{ basesectorupload15mp99mslist[(ansible_play_hosts | length / 2) | int] }}"
        medianstreambufferread15mp99ms: "{{ streambufferread15mp99mslist[(ansible_play_hosts | length / 2) | int] }}"
        medianregistryread15mp99ms: "{{ registryread15mp99mslist[(ansible_play_hosts | length / 2) | int] }}"
        medianregistrywrite15mp99ms: "{{ registrywrite15mp99mslist[(ansible_play_hosts | length / 2) | int] }}"
        
        # Averages
        averagestoragespending: "{{ sumstoragespending | int / ansible_play_hosts | length }}"
        averageuploadspending: "{{ sumuploadspending | int / ansible_play_hosts | length }}"
        averagedownloadspending: "{{ sumdownloadspending | int / ansible_play_hosts | length }}"
        averagefundaccountspending: "{{ sumfundaccountspending | int / ansible_play_hosts | length }}"
        averagecontractfees: "{{ sumcontractfees | int / ansible_play_hosts | length }}"
        averagetransactionfees: "{{ sumtransactionfees | int / ansible_play_hosts | length }}"
        averageaccountbalancecost: "{{ sumaccountbalancecost | int / ansible_play_hosts | length }}"
        averagefundaccountcost: "{{ sumfundaccountcost | int / ansible_play_hosts | length }}"
        averageupdatepricetablecost: "{{ sumupdatepricetablecost | int / ansible_play_hosts | length }}"
        averagetotalallocated: "{{ sumtotalallocated | int / ansible_play_hosts | length }}"
        averageunspent: "{{ sumunspent | int / ansible_play_hosts | length }}"
        averagepreviousspending: "{{ sumpreviousspending | int / ansible_play_hosts | length }}"
        averagetotalspent: "{{ sumtotalspent | int / ansible_play_hosts | length }}"
        averageunspentallocated: "{{ sumunspentallocated | int / ansible_play_hosts | length }}"
        averageunspentunallocated: "{{ sumunspentunallocated | int / ansible_play_hosts | length }}"
        averagedownloadscost: "{{ sumdownloadscost | int / ansible_play_hosts | length }}"
        averageuploadscost: "{{ sumuploadscost | int / ansible_play_hosts | length }}"
        averageregistryreadscost: "{{ sumregistryreadscost | int / ansible_play_hosts | length }}"
        averageregistrywritescost: "{{ sumregistrywritescost | int / ansible_play_hosts | length }}"
        averagerepairdownloadscost: "{{ sumrepairdownloadscost | int / ansible_play_hosts | length }}"
        averagerepairuploadscost: "{{ sumrepairuploadscost | int / ansible_play_hosts | length }}"
        averagesubscriptionscost: "{{ sumsubscriptionscost | int / ansible_play_hosts | length }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: True

    - name: Print final result
      debug:
        msg: |
          TotalNumFiles: {{ sumnumfiles }}
          TotalStorage:  {{ sumnumfiles }}

          MedianBaseSectorUpload(p99): {{ medianbasesectorupload15mp99ms }}
          MedianStreamBufferRead(p99): {{ medianstreambufferread15mp99ms }}
          MedianRegistryRead(p99):     {{ medianregistryread15mp99ms }}
          MedianRegistryWrite(p99):    {{ medianregistrywrite15mp99ms }}

          ContractSpending:
            Average Total Allocated:         {{ averagetotalallocated }}
            Average Total Spent:             {{ averagetotalspent }}
              Average Storage:               {{ averagestoragespending }}
              Average Uploads:               {{ averageuploadspending }}
              Average Downloads:             {{ averagedownloadspending }}
              Average FundAccount:           {{ averagefundaccountspending }}
              Fees:
                Average Contracts:           {{ averagecontractfees }}
                Average Txns:                {{ averagetransactionfees }}
                Maintenance:
                  Average GetAccountBalance: {{ averageaccountbalancecost }}
                  Average FundAccount:       {{ averagefundaccountcost }}
                  Average UpdatePriceTable:  {{ averageupdatepricetablecost }}
            Average Unspent:                 {{ averageunspent }}
              Average Allocated:             {{ averageunspentallocated }}
              Average Unallocated:           {{ averageunspentunallocated }}
            Average PreviousSpending:        {{ averagepreviousspending }}

          EphemeralAccountSpending:
            Average Downloads:       {{ averagedownloadscost }}
            Average Uploads:         {{ averageuploadscost }} (NOTE: still using legacy uploads)
            Average RegistryRead:    {{ averageregistryreadscost }}
            Average RegistryWrite:   {{ averageregistrywritescost }}
            Average RepairDownload:  {{ averagerepairdownloadscost }}
            Average RepairUpload:    {{ averagerepairuploadscost }} (NOTE: still using legacy uploads for repairs)
            Average Subscriptions:   {{ averagesubscriptionscost }}
