- name: Update SSH Authorized keys to Webportals
  hosts: webportals
  gather_facts: False

  # Load common vars
  vars_files:
  - vars/common.yml

  tasks:

    # Add SSH authorized key
    - name: Add SSH authorized key
      ansible.posix.authorized_key:
        user: "user"
        state: present
        # key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6Kcx8yetova4/ALUQHigo/PBMJO33ZTKOsg2jxSO2a user@depl"