- name: Fetch files from Skynet Webportals
  hosts: webportals
  gather_facts: False

  tasks:

    - name: Download portal files to my-logs
      ansible.builtin.fetch:
        src: "{{ webportal_dir }}/{{ item }}"
        dest: "{{ local_logs_dir }}"
      loop:
        - "docker-compose.override.yml"