- name: Setup Skynet Webportals
  hosts: webportals
  gather_facts: False

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True
  
  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"

  tasks:

    # Checks

    # Check '--limit' is used
    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    # Check host OS version
    - name: Check supported OS and version
      assert:
        that:
          - ansible_distribution|lower == 'debian' and ansible_distribution_version == '10'
        fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not yet supported by this role"

    # Server setup

    # User setup

    # Securing server

    # Firewall

    # Portal setup