- name: Restart Skynet Webportals
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"
    docker_compose_build: False
    set_portal_versions: False
    portal_action: "portal-restart"

  tasks:
    # Check '--limit' is used
    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    # Don't restart portals on takedown
    - block:
        - name: Stop play for portals in webportals_takedown group
          debug:
            msg: "Will not restart portal in webportals_takedown group"

        - name: Stop play for portals in webportals_takedown group
          meta: end_host

      when: "'webportals_takedown' in group_names"

    # Check/install Ansible prerequisities
    - name: Include preparing portal prerequisities
      include_tasks: tasks/portals-prepare.yml

    # Disable health check
    - name: Include disabling portal health check
      include_tasks: tasks/portal-health-check-disable.yml
