- name: >-
    Run Shell Commands on Skynet Webportal
    (disable, run commands, test, enable portal)
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: False

  # Target 3 servers at a time.
  serial: 3

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"
    portal_action: "portal-run-shell-commands"

  vars_files:
    - "{{ common_vars_file }}"
    - "{{ custom_vars_file  }}"

  tasks:
    # Check '--limit' is used. This is to protect against taking the entire
    # fleet down
    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    # Check/install Ansible prerequisites
    - name: Include preparing portal prerequisites
      include_tasks: tasks/portals-prepare.yml

    # Disable health check
    - name: Include disabling portal health check
      include_tasks: tasks/portal-health-check-disable.yml
      when: "'webportals_takedown' not in group_names"

    # Execute shell command(s) from yml file
    - name: Include running shell commands
      include_tasks: tasks/shell-commands-run.yml

    # Stop here for portals on takedown
    - block:
        - name: Stop play for portals in webportals_takedown group
          debug:
            msg: "Will not run integration tests, health checks or enabling portals in webportals_takedown group"

        - name: Stop play for portals in webportals_takedown group
          meta: end_host
      when: "'webportals_takedown' in group_names"

    # Run portal integration tests
    - name: Include running portal integration tests
      include_tasks: tasks/portal-integration-tests-run.yml

    # Include running portal health checks
    - name: Include running portal health checks
      include_tasks: tasks/portal-health-checks-run.yml

    # Enable health check
    - name: Include enabling portal health check
      include_tasks: tasks/portal-health-check-enable.yml
      # Do not enable health checks on hosts from out_of_LB group
      when: ('out_of_LB' not in group_names)
