- name: Generate Docker Compose Override File
  hosts: webportals
  remote_user: "{{ webportal_user }}"
  gather_facts: True

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Define playbook vars
  vars:
    max_hosts: "{{ groups['webportals'] | length - 1 }}"

  tasks:
    # Check '--limit' is used
    - name: Fail if you are targeting all dev and prod webportals
      include_tasks: tasks/host-limit-check.yml

    # TODO: Handlers should be configured later as plugins (LastPass/plaintext/
    # Docker secrets/Hashicorp Vault/...)
    - name: Set load/save handlers for secure storage
      set_fact:
        load_portal_config_handler: "tasks/lastpass-load-webportal-config.yml"
        save_portal_config_handler: "tasks/lastpass-save-webportal-config.yml"
        save_cluster_config_handler: "tasks/lastpass-save-cluster-config.yml"

    - name: Include getting portal configs
      include_tasks: tasks/portal-configs-load.yml

    # Generate Docker Compose Override File
    - name: Generate Docker Compose Override File
      include_tasks: tasks/portal-versions-set.yml
