name: Bump Version
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          version-bump: ${{github.event.inputs.version}}
          github-token: ${{secrets.GITHUB_TOKEN}}
