name: Daily
on:
  # Run daily at 1:15am
  schedule:
    - cron: "15 1 * * *"

jobs:
  # Run the linting
  lint:
    uses: ./.github/workflows/lint.yml

  # Check if there were any changes since the last tag
  changes:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      updates: ${{steps.changes.outputs.any == 'true'}}
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1 # Optional fallback tag to use when no tag can be found
      # Use paths-filter to determine which paths have changes
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.previoustag.outputs.tag }}
          filters: |
            any: "**"

  # Make a release if there were changes
  release:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{needs.changes.outputs.updates == 'true'}}
    steps:
      - uses: actions/checkout@v2
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
