name: Lint

on: push

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: make yamllint

  syntax_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check playbooks with --syntax-check
        run: make syntax-check

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install ansible-lint
        run: pip3 install ansible-lint

      - name: Run ansible-lint
        run: make ansible-lint
